### ISSUE TITLE
Bug: Return vehicles on Quick Pick

### ISSUE THREAD

**Issue by Jonneis** [renzuzu/renzu_garage#100]
If you have the car outside and open the garage without the car and use the 'Go To Garage' option and you  take the car from there then you pay the return and u get the car, then when u go to the garage again, the car is not there at all not even in garage or in a quick pick mode.

If you use only the Quick Pick mode then you can return the car again and again without problem

I dont know exactly how you want it to work but i have some suggestions:
• If the EnableReturnVehicles is false maybe to work like you cant see the car at all in the garage until the next server restart.
• Need some info on the garage when you pick if your car got impounded (otherwise you have to remember which car is missing)

[Video](https://streamable.com/d03ma3)

**Comment by renzuzu** [comment]
are you trying to implement , if vehicle is outside, they cannot return it at all?
because i see you dont have the pop up of Pay the valet to return the vehicle.

its possible to do that, do not show the vehicle at all in (inside garage) if its outside.

**Comment by Jonneis** [comment]
No i just removed the pop up return( the Nui call) coz i dont want ppl to return the vehicle coz they spam it(only from the quick pick i it did though)

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_garage/commit/6bca690e3fa468dd6e34f01705fb9219324591ff
