### ISSUE TITLE
Radio wheel and weapon wheel not working after installing renzu garage and dependencies

### ISSUE THREAD

**Issue by StOnEd-SnIpEr** [renzuzu/renzu_garage#109]
I installed ur garage script and the required dependencies,love the garage however it ends up bugging my radio/weapon wheel.
Im not sure if this because of the garage script or 1 of the other dependencies but i would love it if you could find out the cause and fix it.

**Comment by StOnEd-SnIpEr** [comment]
ive looked for errors under f8 and in the tx admin but i find none

**Comment by renzuzu** [comment]
Fix in latest main branch now

**Comment by StOnEd-SnIpEr** [comment]
awesome!!! il go try right now

**Comment by StOnEd-SnIpEr** [comment]
Working smooth,confirmed fixed:)
#legend
