### ISSUE TITLE
Black screen with loading symbol

### ISSUE THREAD

**Issue by StOnEd-SnIpEr** [renzuzu/renzu_garage#110]
If i go to 1 of the private garages in 1 of the smaller houses (for example: West Mirror Drive 28)
it loads up the garage decor and vehicles but if i click on go to garage in the top then the game locks up with a black screen and a loading symbol

**Comment by renzuzu** [comment]
dont use the property garage in the current version theres a known bug, and it will be fully fixed and compatibility with my new housing script soon

**Comment by StOnEd-SnIpEr** [comment]
i didnt spot a option to turn them off in the config of renzu_garage or do you mean i shouldnt use a certain mod?

**Comment by StOnEd-SnIpEr** [comment]
this what you mean??

-- PRIVATE GARAGE CONFIG
Config.Private_Garage = true -- Enable Private Garage system

**Comment by renzuzu** [comment]
> (for example: West Mirror Drive 28)

this is a property garage in older version
this has been removed in latest branch now, update the script
