### ISSUE TITLE
Garage Inventory dont´t open

### ISSUE THREAD

**Issue by olegnapt** [renzuzu/renzu_garage#111]
Hello, 

Why this error when try opening garage inventory ?

![image](https://user-images.githubusercontent.com/90993978/133912730-811601ea-ca77-4a51-be93-e8dff84032e5.png)

**Comment by StOnEd-SnIpEr** [comment]
all i understand with my lack of knowledge of script is that its expecting a table in i think ur database but it can not find it.

**Comment by renzuzu** [comment]
> Hello,
> 
> Why this error when try opening garage inventory ?
> 
> ![image](https://user-images.githubusercontent.com/90993978/133912730-811601ea-ca77-4a51-be93-e8dff84032e5.png)

whats the current version of garage?
are you using the latest one?

**Comment by renzuzu** [comment]
this should be fixed in main branch
