### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by EclipseModding** [renzuzu/renzu_garage#115]
there is a problem in the database because it does not update the stored value
![Screenshot_1](https://user-images.githubusercontent.com/75763087/133937158-abcd6e71-14e6-43e8-aad5-22e188a3dddf.png)

**Comment by StOnEd-SnIpEr** [comment]
i had that issue to. to resolve it i deleted the owned vehicle database and made a fresh one. after that i added into the database bit by bit the blocks of code from his sql file.

**Comment by renzuzu** [comment]
i dont have idea what might cause this?

is this about public garage?

**Comment by EclipseModding** [comment]
this happens in all garages

**Comment by renzuzu** [comment]
in your screenshot its shows 3 private and 1 public garage.

in private, its normal that the store is 0 , because its will not be showed in public_garage.

while the public garage 'A' should store a 1 if stored and 0 if not stored

**Comment by EclipseModding** [comment]
i'm using this phone but every time i go to the garage the vehicles are always out
![Screenshot_2](https://user-images.githubusercontent.com/75763087/133998731-3631530b-f1a1-4ffb-8f54-73fce649f187.png)

https://github.com/coconutwatermelon/hsn-phone

**Comment by renzuzu** [comment]
must be related here
https://github.com/coconutwatermelon/hsn-phone/blob/dfebcbef8477d2c86b3d60604bc8622d1b96ef87/server/server.lua#L1456

checking out a number instead of bool
if you want to check a bool 
use == true instead

this is related to LUA logic 

reopen if you want
Thanks
