### ISSUE TITLE
Inventory not opening

### ISSUE THREAD

**Issue by ElusionPDX** [renzuzu/renzu_garage#116]
Having the same issue with inventory not opening. 
![image](https://user-images.githubusercontent.com/19332765/133940350-bbe69f9e-0d32-45a1-a062-9e89b7a4dcf4.png)
Running newest build of your garage and of [esx legacy ](https://github.com/esx-framework/esx-legacy) with [lindens inventory](https://github.com/rklgaming/linden_inventory/tree/main/linden_inventory).

**Comment by renzuzu** [comment]
this issue seems appear when inventory is empty,
we need to send a empty table instead of a bool false from server.

i have to re examine a fresh install of garage to confirm this

**Comment by renzuzu** [comment]
just confirm using latest branch, the garage inventory error should be not a case now and
inventory is always empty in newly bought private garage.
you have to store modification parts
