### ISSUE TITLE
Impounded vehicles not in impound

### ISSUE THREAD

**Issue by StOnEd-SnIpEr** [renzuzu/renzu_garage#121]
It says it impounded a vehicle but when i go to the impound there is no vehicle

**Comment by StOnEd-SnIpEr** [comment]
just noticed if i do /impound  then it works but if i do f6 for job menu and impound from there it dont work..

**Comment by StOnEd-SnIpEr** [comment]
Also noticed anybody can take out a impounded vehicle. i have Config.Impoundforall = false

**Comment by renzuzu** [comment]
the impound from F6 assuming a Police job.
its does only deletes vehicles, you need to add the execture command for /impound
