### ISSUE TITLE
Vehicle Parts Duplicating

### ISSUE THREAD

**Issue by Streammett** [renzuzu/renzu_garage#126]
in private garages, multiple players - if invited - can dismount and store the same part from a single vehicle.

Example: 3 People in Garage, all 3 can dismount shift leavers level5 from a single vehicle and store it, so there will be 3x shift leavers level5 in stock.

Keep on your awesome work dude!

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_garage/commit/2878382856f0c6f319f94da4eee23aa9acdfbc41
fix Thank you

**Comment by renzuzu** [comment]
let me know if this dont have problem..same logic with renzu_customs
but i forgot if adding + 1 is okay with garages private

**Comment by Streammett** [comment]
still buggy.. nobody could take parts if anyone else already picked it, BUT after removing engine part level4, vehicle gave endless engine parts level2....

Thank You.

**Comment by Streammett** [comment]
and another one: If people buy a garage on a location somebody else already owns, he can see and get all the parts of anyone else who bought this garage.

**Comment by renzuzu** [comment]
fixed

```
your 1st claim about picking up parts is invalid
unless you provide repro steps 
```

**Comment by renzuzu** [comment]
Reopen if theres still a problem
