### ISSUE TITLE
Public garage not working.

### ISSUE THREAD

**Issue by planeklm** [renzuzu/renzu_garage#128]
Hello,
I have a problem with the public garage in this video.
https://streamable.com/zfhr08
I also have another problem where I can see the garage above after using it.

**Comment by renzuzu** [comment]
can you show me the owned_vehicle column for this vehicle plate

**Comment by planeklm** [comment]
![unknown](https://user-images.githubusercontent.com/91488137/135120454-ea233caa-fe81-4d30-b506-56fd5bf989fe.png)

**Comment by renzuzu** [comment]
yea i need to see the owned_vehicle column from SQL
for that plate
so i can tell which one is the problem

**Comment by planeklm** [comment]
![Capture](https://user-images.githubusercontent.com/91488137/135128193-48e13230-3422-4e18-aebb-b42badcbe340.PNG)

**Comment by planeklm** [comment]
Tell me if you need anything else.

**Comment by renzuzu** [comment]
Thata not i meant
I mean the column showing the plate

**Comment by planeklm** [comment]
Sorry I don't know where that is.

**Comment by planeklm** [comment]
![Capture](https://user-images.githubusercontent.com/91488137/135141014-db7a3839-9872-4b1d-9e78-a7d07ff099a1.PNG)
Do you mean this?
