### ISSUE TITLE
Public Garage not working, neither with the police garage and plane hangar.

### ISSUE THREAD

**Issue by planeklm** [renzuzu/renzu_garage#131]
Hello,
I have a problem with the public garage in this video.
https://streamable.com/zfhr08
I also have another problem where I can see the garage above after using it.

**Comment by renzuzu** [comment]
I need to check the plate of vehicle from sql
Heidisql or phpmyadmin

Are you using platespace in config?
In both scripts

**Comment by planeklm** [comment]
I am using place space in the config, this might be why its not working, nothing is in owned_vehicles
![Capture](https://user-images.githubusercontent.com/91488137/135152813-a1967a23-0624-4787-94a2-4a9a6fec0040.PNG)
.

**Comment by renzuzu** [comment]
Your owned vehiclea is empty

Can you show me all the columns there
You might be missing important one

Is this a newly install esx?

**Comment by planeklm** [comment]
![Capture](https://user-images.githubusercontent.com/91488137/135213434-abd47dbc-581e-4e6a-9fd8-bca71a66b011.PNG)
My ESX Version I installed is 1 month old, using The ESX V1 Final

**Comment by renzuzu** [comment]
it seems you need help regarding SQL.
since you did not have any vehicle in your owned_vehicles
its mean the vehicleshop did not save the vehicle to your database.

try buying a vehicle and show me the QUERY

enable the mysql debug using

type mysql:debug 
(server console)
and buy a vehicle using the vehicleshop , let me know whats in there after

**Comment by planeklm** [comment]
I have these errors
![1](https://user-images.githubusercontent.com/91488137/135304940-8e5ea3e5-6408-41e4-a289-e82783ee9a1b.PNG)
![2](https://user-images.githubusercontent.com/91488137/135304944-ff3fe7fe-6401-45bb-b89c-7b00776e8c77.PNG)
,

**Comment by renzuzu** [comment]
Edit
Owned vehicles owner column varchar limit to 64

**Comment by planeklm** [comment]
Thank you so much!

**Comment by planeklm** [comment]
+rep
