### ISSUE TITLE
Disable Blips

### ISSUE THREAD

**Issue by MedicalKush11** [renzuzu/renzu_garage#143]
Hi , i really need to delete some blips but when i delete it some error apear in my consol please can you tell me how i can disable it without bug or error ....

**Comment by renzuzu** [comment]
what blips?

**Comment by MedicalKush11** [comment]
Job Garage blips ans some Heliport

**Comment by MedicalKush11** [comment]
Only blips , this is for the police garage it  show up in map and i dont
want see this blips i only  wanna see public and private garage  if
possible

Le ven. 15 oct. 2021 11 h 32 a.m., renzuzu ***@***.***> a
écrit :

**Comment by renzuzu** [comment]
its not possible right now, i may tweak the config to allow such a thing
