### ISSUE TITLE
FEAT( 1.71 ) : Garage Keys - Vehicle Keys

### ISSUE THREAD

**Issue by renzuzu** [renzuzu/renzu_garage#179]
im currently doing this new feats.
i need input for options below

# Garage Key: (Public garage)
Enable Players to Share garage keys to other players
Enable Other Player to use the same vehicle owned by the original Player

option A: when player share the key, all garages (public) can be access by the other player
option B: when player share the garage key, this garage key (ex. A) are only accessible by other player.

both option is useless if you use non unique garage config.

# Vehicle Keys
Enable you to lock all local vehicles (config)
Enable you to not Auto Start the vehicle ( for lock picking purpose? )
Enable you to lockpick the vehicle (if not owned and not shared)
Enable you to give a copy (or a duplicate) Vehicle Keys to Other Player.
Replacing /transfer with New UI Form to Transfer the Vehicle (give keys)

options : built in lock system (with  UI or no UI)
options :  lockpicking minigame?

**Comment by renzuzu** [comment]
all feats declared has been implimented, and need proper testing before releasing on release download page.
its tags as pre release but i still suggest using the Main branch to get the latest fixes.

for now looks stable.

**Comment by ElusionPDX** [comment]
Some issue we are finding when testing it. 

Gave (temp) key to friend they can lock and unlock but cant start with out hotwiring.

Any way to make it so the temp stay tell you remove them. (Not sure if it does it already as we havnt tried after restarting server again)

cant enter /parked cars when you have keys.

cant find were vehiclekeys table is called in the server side at all to self error check things.

**Comment by renzuzu** [comment]
i will add the vehiclekeys to save in DB
so even if you delete it there will be still a permmision

**Comment by ElusionPDX** [comment]
I think its a good thing to have it save in sql as a random crash could lead to a planned out bank job going bad or something as they no longer have keys lol. 

Just trying to think of stuff that would help for peoples RP with having a key sharing system. 
Is there a way to make it so it can read the vehicles key table to see if you have a key for a parked car that way the owner can park X car for friend in his driveway and the friend can unpark it when they get there.

**Comment by ElusionPDX** [comment]
Some some issue we are seeing when testing this as much as we can is that when parking (/park) the system says its parked and does its norm delete but never respawns now so the only way to get the vehicle back is to go to the main garage. /parkingmeter Does the same. This is random as day one of update it was working fine and day 3 is been a on and off thing with it. 
Also does not update in the DB with the coords of the park and saying its been parked. 
![image](https://user-images.githubusercontent.com/19332765/140308982-a01a64ae-7b8f-4f36-b15f-78246ff82855.png)


https://streamable.com/df1yyo

**Comment by renzuzu** [comment]
not quite sure yet.; but the cause must be this
https://github.com/renzuzu/renzu_garage/commit/a608ad23b49512b2d30795764cfb150df8cb2409

**Comment by renzuzu** [comment]
So does the latest commit fixes the parkinf issue?

As my test i did exp some vehicle,
Have a bool identifier in share keys thats why it wont store vehicle correctly

**Comment by ElusionPDX** [comment]
The 20 vehicles i tried seemed fine. But will know when more people get on
as the best way to test is live lol
