### ISSUE TITLE
update for Lenzh_chopshop V2 to send to impound

### ISSUE THREAD

**Issue by Copenhagen-Gaming** [renzuzu/renzu_garage#193]
not a issue and not sure where to put it but wanted to share this

this is setup in config

Lenzh_chopshop\config

`Config.AnyoneCanChop = true`
than i added if true it will be RP as the vehicle got impounded, change the server side to

Lenzh_chopshop\server\sv_main

`ESX.RegisterServerCallback('Lenzh_chopshop:OwnedCar', function(source, cb, plate, owner, garage_id, impound)
    local _source = source
    local xPlayer = ESX.GetPlayerFromId(_source)
    local impound = impound
    MySQL.Async.fetchAll("SELECT * FROM owned_vehicles WHERE plate=@plate AND owner=@identifier",{['@identifier'] = xPlayer.getIdentifier(), ['@plate'] = plate}, function(result)
        if result[1] and Config.AnyoneCanChop == true then
            print("Vehicle is owned")
            cb(result[1].owner == xPlayer.getIdentifier())
            Citizen.Wait(5)
            MySQL.Async.execute('UPDATE owned_vehicles SET garage_id = @garage_id, impound = @impound WHERE plate = @plate', {
                ['@plate'] = plate,
                ['@garage_id'] = "impound",
                ['impound'] = 1
            })
            print('impounded')
        else
            cb(false)
            print("Not owned")
        end
    end)
end)`

you can use it if you wish, keep up the good work

**Comment by Copenhagen-Gaming** [comment]
correct, its a common script and if people use your garage than they dont have to script server side for a car being chopped. If i chop a players car without the edit than the car does not go to any garge, it just gets lost so i did that to help others out

**Comment by renzuzu** [comment]
im actually looking for chop 😄 , this is good resource one my friend i help to build a city.
this can be actually more good if it removed vehicle mod

**Comment by ElusionPDX** [comment]
Yessss. This could become grate if it worked like ur customs system but
reversed
