### ISSUE TITLE
Custom turbo

### ISSUE THREAD

**Issue by HorizonStaff** [renzuzu/renzu_garage#202]
Hello, when i use renzu_customs and i buy a custom turbo, if i restart server i dont have turbo sound and the turbo boost.
Thanks

**Comment by renzuzu** [comment]
Did you set true for config?
Conf/main.lua

**Comment by HorizonStaff** [comment]
Yes, i did it

**Comment by HorizonStaff** [comment]
Ok i think i "solve it"
Now i have one last error when i try store some part in private garage
https://i.imgur.com/5loAMwq.png

**Comment by MeckerOpa** [comment]
> Ok i think i "solve it" Now i have one last error when i try store some part in private garage https://i.imgur.com/5loAMwq.png

How did you solved it?
