### ISSUE TITLE
Good idea for your scripts as well as translation to German

### ISSUE THREAD

**Issue by GamingMakingDave** [renzuzu/renzu_garage#203]
Evening Renzu,

I have a concern there unfortunately I can't reach you any other way please contact me docg via DM.

I would have translated your clotheshop, vehicle shop and garage into German, I think that would be a good extension if we had a language that could be used by config together with other users from Sweden etc.

In addition, I would have other ideas because your Gragenscript means that Vehicles Rent is no longer able to do something for it. Speak a tablet

I would stand up for the translation as well as the design of the HTML.

Here my Impound Design in HHTML and more i can send u it.

![impound](https://user-images.githubusercontent.com/87772503/139520216-e552a41c-b160-418e-a63f-cb729c91eec1.jpg)

**Comment by renzuzu** [comment]
good ui, but we already have a UI for form (impound)

**Comment by renzuzu** [comment]
We added translation lua
