### ISSUE TITLE
garage blip name

### ISSUE THREAD

**Issue by fk116** [renzuzu/renzu_garage#205]
I thought add garage name in every blip ? example garage A

**Comment by fk116** [comment]
> Saya pikir menambahkan nama garasi di setiap blip? contoh garage A

**Comment by renzuzu** [comment]
set blip statis to false, 
its in conf/main.lua

**Comment by fk116** [comment]
owhh oke

**Comment by fk116** [comment]
> atur blip statis ke false, di conf/main.lua

Why was the exploding car in the garage again?
