### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by ClimaxKass** [renzuzu/renzu_garage#206]
Hi, im on ESX 1.2 and i ve install
- all SQL ( 0 problem)
- the 4 dependency 
https://github.com/renzuzu/renzu_popui
https://github.com/renzuzu/renzu_contextmenu
https://github.com/renzuzu/renzu_notify
https://github.com/renzuzu/renzu_lockgame 
- one-sync is ok

and the renzu_garage 1.72 dont work for me :/
i ve no blips, no garages etc...
if you can help me bro...  TY

**Comment by renzuzu** [comment]
I did test it multiple times after your report in cfx.
Having no error or any info is unhelpful.

The only way you can so now is use the main branch not the release., Seems you still get the cache from old release.. old release download is broken. Maybe your still using it.

Main branch should fix your issue
File name dhould be like

renzu_garage_main.zip
Rename the folder to renzu_garage
