### ISSUE TITLE
Script starting but no garages...

### ISSUE THREAD

**Issue by lrgjok** [renzuzu/renzu_garage#207]
Since the 1.7... version i don't have any garage.. No blip and no marker on the position .. But the script is starting good, i've the garagekeys command working but not the vehiclekeys command ...OneSync Is enabled on my 64 slots server ... thanks for the help

**Comment by renzuzu** [comment]
your using broken download cache from github
use this 
https://github.com/renzuzu/renzu_garage/releases/tag/v1.722
or the main branch
