### ISSUE TITLE
give vehiclekeys

### ISSUE THREAD

**Issue by polopokky** [renzuzu/renzu_garage#209]
I encountered a problem when I gave my car keys to another player. Other players can pick up the car but can't lock it. Need to re-script renzu_garage every time a car swap occurs.

**Comment by renzuzu** [comment]
You mean gave is transfer key?
Not shared?

**Comment by renzuzu** [comment]
i think this need repro steps as my test failed.

upon transfering to another player
other player get the car keys and car lock permission immediately
older owner lost permmision
