### ISSUE TITLE
make your projects with a language file i have to translate everthing to another language and its annoying when you do big updates 

### ISSUE THREAD

**Issue by ZypsohDEV** [renzuzu/renzu_garage#210]
title

**Comment by renzuzu** [comment]
yea sure, but dont make it sound your demanding this is free bro.

**Comment by ZypsohDEV** [comment]
Sorry it was not my intention to make it sound a demanding i meant as a suggestion/request, im sorry for not expressing the best way, your scripts are amazing

**Comment by renzuzu** [comment]
Ill do it when i wake up bro

Cheers

**Comment by jetpnix** [comment]
You can always make a PR tho

**Comment by ZypsohDEV** [comment]
Well when he does it i will give a portuguese lang instantly

**Comment by renzuzu** [comment]
latest master branch is now with locale folder from /conf/locale/*.lua

**Comment by ZypsohDEV** [comment]
tsym man
