### ISSUE TITLE
not save stickers

### ISSUE THREAD

**Issue by polopokky** [renzuzu/renzu_garage#211]
not save stickers The system will save the sticker only the first time you insert it. Next time you can't change the sticker. Garage won't save it. how do i need to fix this help me

**Comment by renzuzu** [comment]
sticker = livery?
it should save 
or you can provide a vehicle to test and livery #

**Comment by renzuzu** [comment]
probably sorted out with this
https://github.com/renzuzu/renzu_garage/commit/0a01deffb67d9fb10df822bad8042a05c41bf7f9

if you are using renzu_customs update it too.
