### ISSUE TITLE
Vehicle duplicated in Priv Garage and listed in impound

### ISSUE THREAD

**Issue by jetpnix** [renzuzu/renzu_garage#212]
![unknown](https://user-images.githubusercontent.com/60974759/140617632-9a8d1f5b-1fa7-4951-8ad7-10befb36d70e.png)

Same plate in one private garage, and the car can be taken from impound even if it is stored. Using impoundforall and ImpoundedLostVehicle in config. Any idea?

**Comment by renzuzu** [comment]
probably conflict with new impound system, 

updated the client, you can do a test with it., this should ignore private garage id

**Comment by jetpnix** [comment]
just updated it to the commit 313e7ed9d645bf4df5bb2e30fb636837708e014b, problem still occurs
The GEMERA cars were duplicated, because we tried to store the duplicated version from the impound even though it should be stored in the private garage.
![unknown](https://user-images.githubusercontent.com/60974759/140748278-1a9045e3-da73-4b81-b47c-7b828871a58e.png)
![unknown2](https://user-images.githubusercontent.com/60974759/140748303-9905aad6-9522-4964-9e60-3fe337e2fb14.png)

**Comment by renzuzu** [comment]
I have second update after that commit
You should get the whole client.lua or copy the second follow up code after that.


Impound should ignore private id garage.

Of you can still see it

Ot probably does not have a private garage id

**Comment by jetpnix** [comment]
Hmm i still dont understand what you mean by i can still see it. I updated it to your latest commit. I checked by printing the v.garage_id before the if statement at 2185. There is no private to be seen in the f8, even though in the database the garage id is private already

**Comment by renzuzu** [comment]
Ill sort this out aoon..

Im just busy atm for other new release.

Hold on

**Comment by renzuzu** [comment]
re open if issue is existing in Latest Main Branch ( not release download )

**Comment by a3rgames** [comment]
we are still seeing the issue of vehicles getting duplicated between privet garage and impound 

pls help to fix this bug
