### ISSUE TITLE
Vehicle Key System Bug

### ISSUE THREAD

**Issue by Streammett** [renzuzu/renzu_garage#213]
Key- and NPC-carLock-System dont work for me properly. I have to restart Script several times until i dont get these errors:

SCRIPT ERROR: @renzu_garage/server/server.lua:70: table index is nil
SCRIPT ERROR: @renzu_garage/server/server.lua:1375: attempt to index a nil value (field 'GVehicles')
SCRIPT ERROR: @renzu_garage/client/client.lua:4262: attempt to index a nil value (field 'GVehicles')

Anything else is working fine. 

System: ESX legacy, esx_multicharacter, OneSync infinity, GameBuild 2372

Script Versions: latest branch and v1.723 (both tested)

Best regards, Greg.

PS: I prefered the small tabs on the left side of vehicle list you used before to pick vehicle class. Is it possible to make it optional?

**Comment by renzuzu** [comment]
possible cause, the line 70 triggered the error due to the default_vehicles does not have a plate prefix.

other error cause of origin error due to the GVehicles are not populated because of line 70

**Comment by Streammett** [comment]
works like a charm now.

One abidding:

Would you pls implement that entering cars with running engine dont need to be hotwired?

Its hard for Emergency if they have to hotwire a emergency vehicle if they switch seats.

Just another hint: Some of my mission cars need to be hotwired too. 

Config.GiveKeystoMissionEntity = true

**Comment by renzuzu** [comment]
Mission entities are already automatically given a keys to owner of entity.

How you spawn emergency vehicle?

Ex. /car blista

Upon spawning it within 3 sec you will get a keys

Limitation only the owner of entity will be given a key

**Comment by Gameadictive** [comment]
I know u closed this but same error here ESX Legacy 1.8.5 
![fffffff](https://user-images.githubusercontent.com/65845786/197875912-f568ae87-fcf5-42be-bb5d-20f68cbc9302.PNG)

**Comment by Gameadictive** [comment]
When spawning a car police for free not owned.
