### ISSUE TITLE
vehiclekeys issue

### ISSUE THREAD

**Issue by Mclick6** [renzuzu/renzu_garage#214]
What would you suggest I try in order to solve this issue, I receive the following in my console when I enter the /vehiclekeys command in chat. Thank you so much in advance
![vehiclebug](https://user-images.githubusercontent.com/92334924/140666587-ca2744b5-b0c0-4814-98f1-6db8cbf3826f.JPG)

**Comment by renzuzu** [comment]
make sure you used one sync, and there is no error starting the garage.

**Comment by Mclick6** [comment]
It was indeed one sync, thank you!
