### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZypsohDEV** [renzuzu/renzu_garage#215]
renzu_garage/client/client.lua:2185: 'then' expected near 'not'
i got this with the latest version before was working fine

**Comment by jetpnix** [comment]
Go to that line and type `and` after 'private' `v.garage_id ~= 'private' not nearbyvehicles[plate]`
```
if v.garage_id ~= 'private' and not nearbyvehicles[plate] and garageid == v.garage_id and v.impound and ispolice or v.garage_id ~= 'private' and not nearbyvehicles[plate] and garageid == v.garage_id and Impoundforall and v.identifier == PlayerData.identifier then
```

**Comment by ZypsohDEV** [comment]
> Go to that line and type `and` after 'private' `v.garage_id ~= 'private' not nearbyvehicles[plate]`
> 
> ```
> if v.garage_id ~= 'private' and not nearbyvehicles[plate] and garageid == v.garage_id and v.impound and ispolice or v.garage_id ~= 'private' and not nearbyvehicles[plate] and garageid == v.garage_id and Impoundforall and v.identifier == PlayerData.identifier then
> ```

i fixed my self i just wanted renzu to know :)

**Comment by DocBurN** [comment]
fresh install, this error is the first roadblock..

**Comment by renzuzu** [comment]
I was drunk when i edit it on phone
Sorry haha
