### ISSUE TITLE
How to add a garage shell

### ISSUE THREAD

**Issue by Dokman** [renzuzu/renzu_garage#217]
How i can add a garage shell?

**Comment by renzuzu** [comment]
Not an option right now.

Is the garage shell is open source?

**Comment by Dokman** [comment]
i am using bob74_ipl to use it, are the offices garages.

**Comment by renzuzu** [comment]
where do you want to add shell?
right now public garage only uses shell

**Comment by Dokman** [comment]
in the private garage, from the housing system
