### ISSUE TITLE
How to reduce the interaction area

### ISSUE THREAD

**Issue by QuinouDEV** [renzuzu/renzu_garage#218]
Hello, How to reduce the interaction zone with points (House garage for exemple) because The interaction area of ​​the garage is too close to the interaction area of ​​the house, when I press E I therefore enter the garage and I cannot open the house menu

**Comment by QuinouDEV** [comment]
when I press E for enter in the garage I cannot open the house menu because the interaction with differents points is too close*. So if possible, I would like to reduce the area where we can press E to open the garage menu.

PS: sorry for my bad english

**Comment by ElusionPDX** [comment]
You can edit this line to make it a smaller zone 
https://github.com/renzuzu/renzu_garage/blob/7c7b0508c14f0b75bf7748070cdfe473899c9bd7/client/client.lua#L369
