### ISSUE TITLE
hotwiring thoughts.

### ISSUE THREAD

**Issue by ElusionPDX** [renzuzu/renzu_garage#220]
If engine left running no need to hotwire.
this way say you make a player get out his car at gun point you can just hope in and go as the keys are still in it cuz they never shut it off.

**Comment by renzuzu** [comment]
so you mean , leave engine on? if im correct it might be easy to implement

**Comment by ElusionPDX** [comment]
If driver left engine on when they got out then a the next person in it
dont need to hotwire as keys are still in ignition

**Comment by renzuzu** [comment]
Okay this should be related to tweak the entering event
