### ISSUE TITLE
Server error stock install entry Private Garage

### ISSUE THREAD

**Issue by Erani0** [renzuzu/renzu_garage#223]
SCRIPT ERROR: @renzu_garage/server/server.lua:713: attempt to index a nil value (field '?')

**Comment by 4verde** [comment]
me too :((

**Comment by renzuzu** [comment]
use the latest commit

this error is if you dont have a vehicle in garage.

**Comment by Erani0** [comment]
I have the latest Version from Master 
And i have a car in the garage

**Comment by 4verde** [comment]
update to the latest and stay the same

**Comment by renzuzu** [comment]
thanks for keep updating me.
https://github.com/renzuzu/renzu_garage/commit/7f999f9a1a0704bfbb11f34e1472a2ba15ce1a5a

let me know if the latest main branch fixes your issues, this cause is unknown, my FXserver version does not produce this error.
