### ISSUE TITLE
take out the car

### ISSUE THREAD

**Issue by Gomez2k** [renzuzu/renzu_garage#225]
when i take out the car from the public garage, it updates de stored column to 0, but i can open the garage menu and take out the car again, the first car i spawned desapear but i cant do it, any change to make it like... take out the car and cant take it out again.. ?

**Comment by renzuzu** [comment]
i just test the latest main branch. it doesnt show the vehicle if its outside.

are you using old version or your impoundlost vehicle is false?
![image](https://user-images.githubusercontent.com/82306584/142725075-6163faac-e226-41b5-9f0e-5c17ed7e7554.png)

**Comment by Gomez2k** [comment]
i dont have this line, where can i download last version with this line?

**Comment by Gomez2k** [comment]
ok i found it i have ImpoundedLostVehicle = true, but still happening that...

**Comment by renzuzu** [comment]
Fixed in latest main branch
