### ISSUE TITLE
Private Garage Owned Vehicles

### ISSUE THREAD

**Issue by viktorhnu** [renzuzu/renzu_garage#226]
So I've tried the script a few hours ago, tried to store a personal vehicle into a private garage, when entering the garage I can't see my car there. Although if I store a random vehicle created by command I can store it and I'm also able to see it in the garage.

**Comment by renzuzu** [comment]
yea i just notice it when im overhauling the script.
its should be fixed in latest version

**Comment by viktorhnu** [comment]
It works now, thank you for your fast response!
