### ISSUE TITLE
1.725 Garage UI wont open anymore

### ISSUE THREAD

**Issue by Streammett** [renzuzu/renzu_garage#228]
Installed latest version and now Garage UI wont show if i use "E" to open garage.

just a window saying "Opening Garage.... Please Wait..." appears and disappears after bar runs out.

already tried to use your default configuration for test, but same result. switching back to previuos version fixed the problem.

ESX legacy, esx_multicharacter, OneSync Infinity

**Comment by Streammett** [comment]
Installed latest version and now Garage UI wont show if i use "E" to open garage.

already tried to use your default configuration for test, but same result.

ESX legacy, esx_multicharacter, OneSync Infinity

**Comment by BirdF** [comment]
Same issue for me I thought it was just me

**Comment by renzuzu** [comment]
any repro steps , screenshot of server and client.

**Comment by renzuzu** [comment]
should be a ghmatti config
