### ISSUE TITLE
Realistik Parking

### ISSUE THREAD

**Issue by Webby0815** [renzuzu/renzu_garage#229]
If you park vehicles with the command / park and then pull them out again, you lose the tuning settings from the tunerdata table or they are not loaded.

but i can see now that there is a mistake in the normal parking garage as well

**Comment by renzuzu** [comment]
how is it related to garage?
tunerdata?

**Comment by Webby0815** [comment]
You can tune the car with the tuner chip. This saves the data in tuberdata. Only when you park the car is it no longer tuned

**Comment by renzuzu** [comment]
You need to adapt your tuner script

Its not related to garage

Probably vecause of plate format
