### ISSUE TITLE
No spawn vehicle inside private garage 

### ISSUE THREAD

**Issue by 4verde** [renzuzu/renzu_garage#230]
When I keep a vehicle in a private garage, they don't appear inside.

**Comment by renzuzu** [comment]
![image](https://user-images.githubusercontent.com/82306584/142768480-f9300bff-2622-4e55-8df5-5897a155e2aa.png)

using latest main branch.

i remember fixing this few days ago

**Comment by 4verde** [comment]
Thankss!
