### ISSUE TITLE
When try to take impounded car from garage

### ISSUE THREAD

**Issue by Velkostatkar** [renzuzu/renzu_garage#231]
Missing WHRE and How much to pay

![image](https://user-images.githubusercontent.com/70021784/142769018-13f4d968-4e14-4722-a71d-a385db12db9b.png)
![image](https://user-images.githubusercontent.com/70021784/142769103-79bd1d21-00df-42e3-b89c-162deb62134a.png)

**Comment by renzuzu** [comment]
Thanks for screens,

I pushed an update in client/function.lua and server.lua

Tell me if error still exist and about impound info

I cant test yet im on phone
