### ISSUE TITLE
Real Parking ( /park ) - Don't show parking vehicles after server restart

### ISSUE THREAD

**Issue by TrustedPunch** [renzuzu/renzu_garage#232]
Hey!
After a server restart don't spawn parking vehicles and in the garages notify says "you dont have any vehicles".

**Comment by renzuzu** [comment]
If all vehiicles outside that notify will throw.

Verify the vehicle is really in owned_vehicles

Then if its existing in database.

Check any server error or client

The real parkinf spawnes are triggered by playerloaded state
Using one sync , make sure onesync is on

**Comment by TrustedPunch** [comment]
- all cars @ owned_vehicles
- OneSync is enable
- When I go in to the garage and leave there then spawn all parked cars on the map

**Comment by TrustedPunch** [comment]
Last one question - when I parked a car then I can see there @ impound garage - have you a fix?
If you don't have a solution, I'll create one of my own.

**Comment by renzuzu** [comment]
The radius
Ill make a config maybe

If you can edit client files

Find < 50
To edit it

**Comment by renzuzu** [comment]
Marked solved in latest commits
