### ISSUE TITLE
Problems with EnableReturnVehicle

### ISSUE THREAD

**Issue by SanderAli** [renzuzu/renzu_garage#233]
Hello, first of all, thank you for your enormous work.

Now yes, I am using esx_legacy and the latest version of renzu_garage when I take out a vehicle and someone drives it or it is abandoned somewhere on the map, I can claim it, despite having "EnableReturnVehicle = false" and being "true" the "ReturnPayment" option does nothing. I have no errors in the console. If I impound a vehicle if it works fine, the vehicle stops showing up in the garage, but not when someone is driving my vehicle or it is outside the garage parked somewhere.

**Comment by renzuzu** [comment]
Actually i cant reproduce this problem, some people report it too..

But in my case all vehicles in outside are nor showing in vehicle list from garage.

Ao probably config setting you can share

**Comment by SanderAli** [comment]
this is what the main looks like
![main](https://user-images.githubusercontent.com/45070518/142906360-339b487c-e2cd-4a48-8798-81258c341cfc.png)
this is what the impoundlooks like
![impound](https://user-images.githubusercontent.com/45070518/142906377-f4c2a6e6-9a60-4ffe-a246-10d0f7aa83f4.png)
Here is an image of the database "owned_vehicles"
![bd](https://user-images.githubusercontent.com/45070518/142906394-e540ddb6-e4ff-43ad-9be9-3c07a6eeae2f.png)
The only strange thing that I have been able to notice in the F8 console, I do not know if it is important, is that when I open the garage those notices appear.
![console](https://user-images.githubusercontent.com/45070518/142906402-247391b6-826f-4391-bce4-15fe7033c270.png)

**Comment by renzuzu** [comment]
Try using main branch
Your screen shows you use old version.

And stores is 1
It means ita in garage.
Is that supposed to be outside?

**Comment by SanderAli** [comment]
The version I'm using is 1.725.

It was just opening the garage, and showing him the message that comes out on f8.

I can show you better by recording a mini video of the event, if you think it is better?

**Comment by renzuzu** [comment]
> And stored column from owned_vehicles is 1
> It means its in garage.
> Is that supposed to be outside?

This

**Comment by SanderAli** [comment]
When I take out the vehicle it says 0, but I left them stored in the garage, that's why it comes out 1.

Even at 0, I can claim the vehicles as if they were inside.

**Comment by renzuzu** [comment]
Ok thanks for info

One last thing
Can you tell me fxserver?

I will debug this

Might be related to 1 and 0 as boolean thing.
Issue in lua

**Comment by SanderAli** [comment]
Here you have a video set with "EnableReturnVehicle = false"
https://streamable.com/rpymcc

fxserver = 3922

**Comment by renzuzu** [comment]
updated main branch
![image](https://user-images.githubusercontent.com/82306584/142989206-ae5c965f-e3f4-4c6f-9dbe-91f78dd880d1.png)

please test. before i release it in release page (download)

**Comment by SanderAli** [comment]
Great job, problem solved.

**Comment by renzuzu** [comment]
glad to hear
