### ISSUE TITLE
Take Out Car Problem

### ISSUE THREAD

**Issue by Gomez2k** [renzuzu/renzu_garage#235]
when i take out the car from the public garage, it updates de stored column to 0, but i can open the garage menu and take out the car again, the first car i spawned desapear but i cant do it, any change to make it like... take out the car and cant take it out again.. ?
I have ImpoundedLostVehicle = true, and im using the last version of the script

**Comment by Gomez2k** [comment]
Im new on this things, but i think that in some line you make the sql change the garage_id to some impound garage, exemple, car is on garage A, if i take it out, the car will go to MRPD_impund, maybe can force it in some line, what you think?

**Comment by renzuzu** [comment]
Use latest uodate this is fixied thanks

**Comment by Gomez2k** [comment]
ur a god
