### ISSUE TITLE
open publci garage

### ISSUE THREAD

**Issue by DvScriptsSK** [renzuzu/renzu_garage#236]
When I go to the pubic garage I can not see the notify to open garage
and when i park car it delete and spawn

**Comment by renzuzu** [comment]
Install renzu_notify

Delete and spawn
Its a real parking

Change the keybind in config or disable it

**Comment by DvScriptsSK** [comment]
I have renzu notify i try disable parking

**Comment by DvScriptsSK** [comment]
When i park cár IT will park and spawn other

**Comment by DvScriptsSK** [comment]
Can i contact you on discord or somethink

**Comment by DvScriptsSK** [comment]
this is my config Config = {}
Config.Locale = "en" -- en,es, or any language support
--GENERAL SETTING
Config.Mysql = 'ghmattisql' -- "ghmattisql", "mysql-async", "oxmysql"
Config.use_RenzuCustoms = true -- Use renzu_customs getter and setter for Vehicle Properties
Config.ReturnDamage = true -- return visual damage when restoring vehicle from garage
Config.ReturnPayment = 1000 -- a value to pay if vehicle is not in garage
Config.UseRayZone = false -- unrelease script https://github.com/renzuzu/renzu_rayzone
Config.floatingtext = true -- use native floating text and marker to interact with garages (popui and floatingtext must be opposite settings) (popui must be false if this is true)
Config.UsePopUI = true -- Create a Thread for checking playercoords and Use POPUI to Trigger Event, set this to false if using rayzone. Popui is originaly built in to RayZone -- DOWNLOAD https://github.com/renzuzu/renzu_popui
Config.Quickpick = false -- if false system will create a garage shell and spawn every vehicle you preview
Config.UniqueCarperGarage = false -- if false, show all vehicles to all garage location! else if true, Vehicles Saved in Garage A cannot be take out from Garage B for example.
Config.GarageKeys = true -- Enable Player to Give Public Garage Keys to enable vehicle sharing
-- BLIPS --
Config.BlipNamesStatic = true -- if true no more garage a garage b blip names from MAP , only says  Garage
--GENERAL SETTING

-- VEHICLE IMAGES
Config.use_renzu_vehthumb = false


Config.EnableImpound = true -- enable/disable impound
Config.EnableHeliGarage = true -- enable/disable Helis
Config.PlateSpace = true -- enable / disable plate spaces (compatibility with esx 1.1?)
Config.Realistic_Parking = false
Config.ParkButton = 38 -- E
Config.EnableReturnVehicle = false -- enable / disable return vehicle feature
Config.DefaultPlate = 'LOSSANTOS' -- default plate being used to default_vehicles args

-- MARKER
Config.UseMarker = true -- Drawmarker
Config.MarkerDistance = 20 -- distance to draw the marker
--MARKER

-- PROPERTY / HOUSING GARAGE
Config.EnablePropertyCoordGarageCoord = true  -- set to false if you will use custom exports and events
Config.HousingBlips = false
-- TriggerEvent('renzu_garage:property',"Forum Drive 11/Apt13", vector3(-1053.82, -933.09, 3.36)) -- example manual trigger
Config.PropertyQuickPick = true -- quickpick -- deprecated method 1.72
Config.UniqueProperty = true -- if enable , only stored vehicles in this Property ID will be show -- deprecated 1.72
Config.PrivateHousingGarageEnable = true -- will use IPL garages , small, medium, large (same with private garage) if this is false, it will use normal garage function like Public garage, quick pick menu

**Comment by DvScriptsSK** [comment]
when i park it i pay 5k and respawn the vehicle

**Comment by DvScriptsSK** [comment]
![image](https://user-images.githubusercontent.com/72212575/143080957-c0303ae8-46c0-4b0b-a315-fc7cfa4de4c9.png)
![image](https://user-images.githubusercontent.com/72212575/143080977-931edf7e-ef50-4dfd-a1c2-c06bc2538833.png)

**Comment by renzuzu** [comment]
Its said you missed column type

Import all column one by one per line

**Comment by DvScriptsSK** [comment]
Ok i will try
