### ISSUE TITLE
I Can not return my vehicle when IS like Exploded

### ISSUE THREAD

**Issue by DvScriptsSK** [renzuzu/renzu_garage#239]

**Comment by renzuzu** [comment]
Can you explain a bit more?
Exploded?

**Comment by DvScriptsSK** [comment]
You like ride in cire and it broke like explode or somethink but you can not pay in garage for returning vehicle beck

**Comment by DvScriptsSK** [comment]
i can not return vehicle when is somewhere out

**Comment by Seth2210** [comment]
> i can not return vehicle when is somewhere out

i have the same issue did u find a solution?
