### ISSUE TITLE
Marker to enter house garage

### ISSUE THREAD

**Issue by aiden-28** [renzuzu/renzu_garage#240]
hi how do i reduce the marker showing as its conflicting with the option to enter my houses please if u can help

link to screenshot https://gyazo.com/6cbd11992dedddaa2db6479909932eab

**Comment by renzuzu** [comment]
the latest commits is only 3 radius,
you can edit it on the client side

**Comment by renzuzu** [comment]
![image](https://user-images.githubusercontent.com/82306584/143327147-3fac9e3a-72fb-4421-8323-483ffb05bc0e.png)

**Comment by aiden-28** [comment]
Thanks so much!
