### ISSUE TITLE
I have a error with the garge at the Legion Square

### ISSUE THREAD

**Issue by Seth2210** [renzuzu/renzu_garage#242]
i only change Cofig.Mysql so the script can work. now i get this error code:

[ script:renzu_garage] SCRIPT ERROR: @renzu_garage/conf/main.lua:105: attempt to call a nil value (field 'showNotification')

if i go the the line 105 i cant see a problem. i then changed:  "Config.Renzu_notify = false -- if false we will use default framework notification" from false to true. 
and now i get this error: [    c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[ script:renzu_garage] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.

hope you can help me

**Comment by Velkostatkar** [comment]
somethink like that problem at my server.
but I dont get the error 105.. Only notifications dont work. 

Here is a notification error
![image](https://user-images.githubusercontent.com/70021784/144743337-333a1ff0-8e01-49ed-a19e-891fb78da6b0.png)
