### ISSUE TITLE
Problem with Housing Garage

### ISSUE THREAD

**Issue by Driftmonkey06** [renzuzu/renzu_garage#245]
Hi, like the title say i have a problem with housing garage, i can buy a garage, put my car in it, but then when i enter in the garage the car is not here, no error at all

i tried private garages, public garage etc all work fine but not the housing garage

also i checked in the database and this is what it write ( first line is a private garage, the second is the housing garage )
![image](https://user-images.githubusercontent.com/46659165/145822632-0770a3aa-78e8-412b-bf08-469504251eaf.png)

i didnt edited the script, just edited some config to my liking thats all
maybe i did something wrong, but i dont think

**Comment by peppinoita** [comment]
Same issue, this is the error:
![image](https://user-images.githubusercontent.com/12203647/147570439-de18018a-90ca-4769-861b-ef915c1b244e.png)
```
    if newgarage then
        local shell = id
        if housegarage[id] ~= nil then
            shell = housegarage[id].shell
        end
        local pgarage = deepcopy(private_garage[shell].park)
        for k,v in pairs(pgarage) do
            vehiclesgarage[k] = v
            if v.vehicle == nil then vehiclesgarage[k].taken = false end
            if not vehiclesgarage[k].taken and k == #pgarage then
                vehiclesgarage[k].taken = true
                vehiclesgarage[k].vehicle = prop
                break
            end
        end
    end
```

**Comment by MapGod** [comment]
Im having the same issue as peppinoita and Driftmonkey06

**Comment by VE7KND** [comment]
Same here as well. Housing garages are bugged. Private and public garages seem to be working fine?

**Comment by VE7KND** [comment]
@peppinoita - Use mysql-async, not oxmysql.

**Comment by QuarterMileRP** [comment]
First off, really like your work Renzu, but I'm having the same issue as peppinoita, but I'm using mysql-async.  @PatientXero , appreciate your input, any other suggestions? The garage I'm trying to use is #176 in the config file, FYI
