### ISSUE TITLE
GlobalState GVehicles not sharing to client side

### ISSUE THREAD

**Issue by baguscodestudio** [renzuzu/renzu_garage#248]
We have 3000+ rows of owned_vehicles, the caching takes long not surprising. But the problem is the GlobalState.GVehicles doesn't get sent to the client side so whenever the user presses J to lock or unlock vehicle, it creates this error.
![image](https://user-images.githubusercontent.com/60974759/146867992-81870ac4-7add-48d8-abff-21631a9d74fc.png)
Did some debugging to make sure it really did work on the server side, printed globalstate.gvehicles, it did print it out. But on the client side printed out Gvehicles, it was null.
Now i tried to delete 500 rows, and restarted the script it worked. And i have made sure to press J after the caching was done. Any idea?

**Comment by MeckerOpa** [comment]
Same issue here
