### ISSUE TITLE
Vehicles saying not Owned

### ISSUE THREAD

**Issue by ComradGamingMC** [renzuzu/renzu_garage#259]
Hello, So when I purchase a vehicle from the vehicle shop (Using your Vehicle shop) When I drive to the garage and attempt to store it is says Vehicle is not owned ( https://medal.tv/games/gta-v/clips/83TSJ-P3oqYxH/d13371N4XTFQ?invite=cr-MSxJSm4sMTc4ODk4NDgs )

No Errors showing up in Console, or in F8 Console 

[script:renzu_vehicle] BUYING START	baller6
[script:renzu_vehicle] BUYING VEHICLES SAVED FROM Cofnig vehicles tables
[script:renzu_vehicle] RESULT FETCHED
[script:renzu_vehicle] BUY DONE
[script:renzu_vehicle] Sending Keys
[script:renzu_vehicle] SENDING TO CLIENT SUCCESS
[ script:renzu_garage] table: 000001E18D028080	gago
[ script:renzu_garage] JPS 638	Newly Owned Vehicles Found..Adding to Key system
[ script:renzu_garage] JPS 638	Already Owned Vehicles Spawned by other identifier... giving keys to network entity owner

Thats all that is showing when buying a vehicle and trying to store it.

**Comment by ComradGamingMC** [comment]
[fxserver_1642579452.log](https://github.com/renzuzu/renzu_garage/files/7895159/fxserver_1642579452.log)


This is also the Server log when i start the server. No Errors for this script

**Comment by duckysuck** [comment]
this bit looks wrong
[ script:renzu_garage] JPS 638 Already Owned Vehicles Spawned by other identifier... giving keys to network entity owner
