### ISSUE TITLE
CAR NOT FOUND

### ISSUE THREAD

**Issue by VTRPSTAFF** [renzuzu/renzu_garage#26]
The script appears to be functional, but does not recognize the cars I have in my garage or the cars that are just bought. 
I put everything right, be it dependency, either SQL or even start order. 
I'm using the ESX V1 Final. 
Picture: https://i.imgur.com/28qkEtD.png

**Comment by renzuzu** [comment]
Hi

are you using vehicles table?
with name ,model column?

the garage are using this to fetch the Vehicle Name

incase it fails i commit a change to use a Labeltext
https://github.com/renzuzu/renzu_garage/commit/64f355bc4ec328aa45759f72c71b8a382e87e8c8

but you should check if you are using a vehicles table with name,model columns on it.

**Comment by VTRPSTAFF** [comment]
Yes im using it.
I will test this change

**Comment by Decodaz** [comment]
Are the "CARNOTFOUND" Cars Addon Vehicles?

**Comment by VTRPSTAFF** [comment]
Yes
