### ISSUE TITLE
renzu_jobs Public Inventory Stash Error

### ISSUE THREAD

**Issue by rickman0930** [renzuzu/renzu_garage#260]
hi boss renzuzu :) do i need sql tol work the public inventory stash food tray in burgershot and beanmachine? all is working for me  :) only the food tray stash having an issue.. im using esx 1.2 and esx_inventoryhud 2.4.0.. thank you so much 💯 

this is the error i recieved

[script:esx_addonacco] SCRIPT ERROR: SCRIPT ERROR: @renzu_jobs/server.lua:37: attempt to index a nil value (local 'account')
[script:esx_addonacco] > ref (@renzu_jobs/server.lua:37)
[script:esx_addonacco] > <unknown> (@mysql-async/mysql-async.js:14959)
[script:esx_addonacco] 
[script:esx_addonacco] (nil stack trace)> txaReportResources

**Comment by peppinoita** [comment]
you miss job data on database.

**Comment by rickman0930** [comment]
> you miss job data on database.

i already put the burgershot sql and all stocks inventory is working now.. but the stash or public inventory for all players in the food tray is not working..

**Comment by rickman0930** [comment]
i try also to copy and paste the code to other whitelisted job like police and ambulance via config.. its working but only police job can only share and get the items inside the public tray,, so if you are in a policejob and put something in the tray. only police job can only  see and get the item.. hope we have food tray inventory for all players in the city :) the renzu_jobs is really awesome.. best script tnx renzuzu
