### ISSUE TITLE
Oxmysql not working

### ISSUE THREAD

**Issue by duckysuck** [renzuzu/renzu_garage#261]
After changing config to oxmysql and execute to query and fetchSync to query_async in sv_wrapper I'm getting fetch issues still. Trying to unpick this without ripping out everything I dont need.

Error
[ script:renzu_garage] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:881: No such export fetch in resource oxmysql

**Comment by peppinoita** [comment]
In the config do not choose oxmysql, leave to mysql-async.
oxmysql has been reqorked in order to be used as mysql-async
