### ISSUE TITLE
Unable to store vehicle in public garage it will not delete

### ISSUE THREAD

**Issue by MrDankle** [renzuzu/renzu_garage#262]
When trying to store into the public garage the car does not dissapear/delete even thought it does add it back to the garage meaning it can be duped. I am running with realistic parking off in config (as when i tried that anythingn i parked went straight to impound but annoyingly these did dissapear) and have tried both branch and latest. also i have another issue with both versions where i can enter a private garage and choose a vehicle but it does not spawn me back out. i saw tha there were fixes for this and changed version and didnt fix it.. I have no errors in the console and everything else like impounds etc seem to work fine. I have all dependencies and SQL correctly insalled.

**Comment by MrDankle** [comment]
I believe its the following not working it does not do the delete part but does make you exit the vehicle... Any helo would be very much appreciated.

TriggerServerCallback_("renzu_garage:changestate",function(ret)
        local ent = Entity(vehicle).state
        if ret or ent.share and ent.share[PlayerData.identifier] then
            DeleteEntity(vehicle)	
			
        end

**Comment by NitroX28** [comment]
Hey have you found any fix ? @MrDankle

**Comment by LSatan** [comment]
Hello I also work with advanced parking and had the same problem. However, I solved it quickly and easily. Go to file: renzu_garage/client/function.lua.  Go to line 188 : function Storevehicle(vehicle,impound, impound_data, public). Add the following to row 208: TriggerServerEvent("AdvancedParking:deleteVehicle", vehicleProps.plate, false). then it works.
``` C++
function Storevehicle(vehicle,impound, impound_data, public)
    local vehicleProps = GetVehicleProperties(vehicle)
    local garage___id = garageid
    if garage___id == nil then
        garageid = 'A'
        garage___id = 'A'
    end
    if impound then
        garageid = impound_data['impounds'] or impoundcoord[1].garage
        garage___id = impound_data['impounds'] or impoundcoord[1].garage
    end
    Wait(100)
    TaskLeaveVehicle(PlayerPedId(),GetVehiclePedIsIn(PlayerPedId()),1)
    Wait(2000)
    TriggerServerCallback_("renzu_garage:changestate",function(ret)
        local ent = Entity(vehicle).state
        if ret or ent.share and ent.share[PlayerData.identifier] then
            DeleteEntity(vehicle)       
		end
    end,vehicleProps.plate, 1, garage___id, vehicleProps.model, vehicleProps, impound_data or {}, public)
    TriggerServerEvent("AdvancedParking:deleteVehicle", vehicleProps.plate, false)--------------------------------------------------------------------------------
    neargarage = false
        if impound then
	   DeleteEntity(vehicle)
        end
	
	
end
```
[functions.lua.txt](https://github.com/renzuzu/renzu_garage/files/8288116/functions.lua.txt)
I hope I could help. Regards
