### ISSUE TITLE
Private Garage not working.

### ISSUE THREAD

**Issue by CaptionPrice1** [renzuzu/renzu_garage#283]
The UI pops out but if u press E to start buying nothing happens?

Can someone help?

**Comment by Dokman** [comment]
error

[ script:renzu_garage] SCRIPT ERROR: @renzu_garage/server/server.lua:571: attempt to index a nil value (field '?')
[ script:renzu_garage] > handler (@renzu_garage/server/server.lua:571)
[ script:renzu_garage] > Query.onResult (@oxmysql/dist/build.js:21740)
[ script:renzu_garage] > <unknown> (@oxmysql/dist/build.js:11918)
[ script:renzu_garage] > processTicksAndRejections (node:internal/process/task_queues:78)

**Comment by Dokman** [comment]
@renzuzu Can you fix it?

**Comment by cityparadise** [comment]
![image](https://user-images.githubusercontent.com/108126483/175513995-9d656452-20f9-4f72-969a-ad4b475d65a7.png)
this is the problem i get can anyone to help me because my private garages aren't working

**Comment by hasidu** [comment]
i have it fixed
