### ISSUE TITLE
carkey not work

### ISSUE THREAD

**Issue by polopokky** [renzuzu/renzu_garage#289]
![image](https://user-images.githubusercontent.com/73616076/183450195-3a0f9454-1434-4a30-82cf-5056510e9817.png)

**Comment by mrvn7rp** [comment]
I have the same issue since I updated the server to the latest sable artifacts.
Someone has an idea whats the problem?

**Comment by mrvn7rp** [comment]
nevermind, I just saw there is a new release :D
