### ISSUE TITLE
store vehicle cannot get out (pop UI not show)

### ISSUE THREAD

**Issue by fraddya** [renzuzu/renzu_garage#293]
Not sure why its not work no any error in F8 or console but pop ui  or floting text not show also garage blip not show in map white Config.BlipNamesStatic = true this command is "FALSE"

**Comment by Tamer173** [comment]
Sorry for another issue,

Hi Renzuzu , i have seen your scripts are a Big contribute to the fivem society and you are making it fun for all of us it will be so much easier for you and all the other members using your script, if you can make a discord server. I hope you will look into it.

**Comment by Tamer173** [comment]
> Not sure why its not work no any error in F8 or console but pop ui or floting text not show also garage blip not show in map white Config.BlipNamesStatic = true this command is "FALSE"

i am having the same issue i can store owned vehicle but cannot take the vehicle out although the ui appers then my character freezes
![image](https://user-images.githubusercontent.com/105336574/194704535-5f31b8f1-ac1e-4632-8241-428ca3895c9c.png)

![image](https://user-images.githubusercontent.com/105336574/194704647-9d482f64-f8d6-403e-9602-0c0ecebaf113.png)
