### ISSUE TITLE
Failed to load Script

### ISSUE THREAD

**Issue by BrasX** [renzuzu/renzu_garage#295]
Hey guys, i tryed Renzu Garages, but its not loading 4 me.....

here u get an Screenshot, this say failed to load script @ renzu_shield/init.lua.
but that script not exist, please help me :I

![304e11a2b131744d33daa0d5947ec442](https://user-images.githubusercontent.com/46135771/198853776-2fab25ad-b4f2-4505-ad85-ba0dc573294c.png)

best regards

**Comment by renzuzu** [comment]
the latest main branch needs ox inventory and ox_lib to work
and that error should be ignored it should work with or without that. 
you can also remove it on fx manifest
