### ISSUE TITLE
impound job grades

### ISSUE THREAD

**Issue by Ra78u6** [renzuzu/renzu_garage#299]
Super script! best garage/shop/customs ever. 

But i have a question, The jobs can look into the impounds, but its a bit weird all the grades can look into the impound.

plzz can you look at it :)

**Comment by renzuzu** [comment]
yes , its setup to work with any grades.

i can make it to view the impound only if grade has not met.
and setup it with
grade = {
  [1] = false, -- grade 1 can only view
   [2] = true, -- grade 2 can take out impounded vehicle
}
as for example

**Comment by Ra78u6** [comment]
Oh thxx. Do i need to add that to the impound config?

**Comment by renzuzu** [comment]
no this is to be added on next patch.

**Comment by Ra78u6** [comment]
thx mate

**Comment by Ra78u6** [comment]
oh btw we have one other problem, we have a normal vehicleshop as a custom cardealer beside your vehilceshop. everyting works. even the saving in your garage system, but the your car lock system sometimes doesnt work. we tried to get it working kind of with impounding. Sometimes it works, sometimes not. only the cars that came from the other vehicle shop.  Do you maybe know a solution? i just found out if we restart the server it works on the other cars :), but its weird

**Comment by Ra78u6** [comment]
we get this error close to locking problem
![image](https://user-images.githubusercontent.com/117487472/200137089-6dcbff72-1fb2-4902-ae9a-9db88eb438b1.png)

![image](https://user-images.githubusercontent.com/117487472/200137092-8b00946d-bc49-41c2-81a4-4c35d2f84a40.png)

**Comment by Ra78u6** [comment]
oh it seriously works restart on the key system thxxxx for your help mate

best script ever! i love your work

**Comment by Ra78u6** [comment]
do you maybe know wich date the new patch is coming?
