### ISSUE TITLE
Car Keys, Garage Keys as items

### ISSUE THREAD

**Issue by Gameadictive** [renzuzu/renzu_garage#301]
I´m trying buying a car and not keys given.
Taking out a vehicle from garage and not keys given.

I have ox_lib and ox_inventory, no errors in clientside or serverside.

When i use the command garagekeys UI opens
When use the vehiclekeys UI not opening and still no errors.

I´m in the RequestDuplicateCoord and i can use the menu but is not giving me any key from any car.

SOLUTION: I forgot to add 

['keys'] = {
		label = 'Vehicle Key',
		weight = 0,
		stack = false,
		close = true,
		description = 'Vehicle Key'
	},
	
In ox_inventory
	
Now is other problem out there

When somebody gets out a car from the garage it comes with the key but if you give the key to other person, he can open your car but if he gives you back the keys u can´t open or close it.

And you can open/close vehicles without the key of the vehicle.

After a restart with Vanilla Vehicles it seems working fine maybe is something with Addon Cars? I will still testing.
Yep i test it with Addon Cars and keys are not working fine. You can still open or close and drive without the keys.

Any export to add this function that when u spawn a vehicle from other script then you get he keys of the vehicle?

**Comment by Gameadictive** [comment]
I have ox_lib and ox_inventory, no errors in clientside or serverside.

**Comment by Gameadictive** [comment]
Now is other problem out there

When somebody gets out a car from the garage it comes with the key but if you give the key to other person, he can open your car but if he gives you back the keys u can´t open or close it.

**Comment by Gameadictive** [comment]
And you can open/close vehicles without the key of the vehicle.

**Comment by renzuzu** [comment]
> Any export to add this function that when u spawn a vehicle from other script then you get he keys of the vehicle?

https://github.com/renzuzu/renzu_garage/commit/6ba82411ae2add0d00d326d11dda02417814468a

this is server based export

exports.renzu_garage:GiveVehicleKey(plate,source)
@plate = plate of vehicle
@source = id of player

> When somebody gets out a car from the garage it comes with the key but if you give the key to other person, he can open your car but if he gives you back the keys u can´t open or close it.

as for this can you help to reproduce this problem?
this should be not the case because when you receive the item again from other player.
the metadatas from item should be still there

are you using updated ox_inventory?

**Comment by Gameadictive** [comment]
Yes, i can help to reproduce the error. and yes im using last version of ox_inventory

**Comment by Gameadictive** [comment]
`When somebody gets out a car from the garage it comes with the key but if you give the key to other person, he can open your car but if he gives you back the keys u can´t open or close it.`

Is addon car related and it was owned cause i use esx_givevehicle. Tested with a divo. But well is pretty bugged all the key part, can i tell you all the things here?

**Comment by Gameadictive** [comment]
1. I have a problem where NPCs when park they cars the car disappears.

2. When someone strays too far from a vehicle that belongs to them and it disappears because it is eliminated and I don't know why they are eliminated, it does not return to the impound or the garage, when they go to the garage to remove it they get the message that they are already out but Everything disappears except the mouse.

4. When you steal a vehicle from an NPC that is on the street everything is fine but if you get off and try to get on it again it is closed, if you use /lockpick or the inventory lockpick it lets you get on and start it but if you get off it no longer lets you use it /lockpick or the item.

**Comment by renzuzu** [comment]
How do you spawned the addon? Does its spawned from garage i just need to confirm this first.

>I have a problem where NPCs when park they cars the car disappears

What does this mean? The local npc parked it? And car diasapear? Or player is parking local vehicle?

>When someone strays too far from a vehicle that belongs to them and it disappears because it is eliminated and I don't know why they are eliminated, it does not return to the impound or the garage, when they go to the garage to remove it they get the message that they are already out but Everything disappears except the mouse and is not car

Entity will be deleted if no players is around. Its one sync feature.

But if the garage saying its already out and you cant find it on impound. Its mean the resource still see your vehicle plate in the area.

Maybe i should change the anti duplicate checker logic

Instead deletes it and spawned a new one.
Its becoming always issue in when i cant reproduce it on my local.

>When you steal a vehicle from an NPC that is on the street everything is fine but if you get off and try to get on it again it is closed, if you use /lockpick or the inventory lockpick it lets you get on and start it but if you get off it no longer lets you use it /lockpick or the item

This is a known bug that i alway have forgot to fix.
As i dont use local npc so i always forget.
This can be fix in next commit.

**Comment by Gameadictive** [comment]
> How do you spawned the addon? Does its spawned from garage i just need to confirm this first.

**Comment by renzuzu** [comment]
none for now, im gonna test it now, thanks for help. ill update this when im done :)

>The local npc parked it in a park lot and the car 'boom' instantly dissapears.
this does not have to do with the garage, i promise you.
unless some parked (realistic) is already spawned there and it take over the position its possible.

**Comment by Gameadictive** [comment]
> this does not have to do with the garage, i promise you.
> unless some parked (realistic) is already spawned there and it take over the position its possible.

Probably i do something weird. I will check it and info here. Thank you renzu for all your scripts, are awesome

**Comment by Gameadictive** [comment]
Yes the car local parked thing was other resource, thanks for check it.

**Comment by Gameadictive** [comment]
Sorry im not very good with english, you mean you are working on that ?

**Comment by renzuzu** [comment]
What i mean is i fix this. But its not in release download.

Its on direct download button, called main branch of repo

**Comment by Gameadictive** [comment]
I will download and test it

**Comment by Gameadictive** [comment]
This is the only error that i see
![Whatisthis](https://user-images.githubusercontent.com/65845786/201165684-ff952f7e-af89-4528-a6ec-2543dbaa7267.PNG)

**Comment by Gameadictive** [comment]
![otherthere](https://user-images.githubusercontent.com/65845786/201178212-25cc9204-da6d-4ed6-8c93-43d72dc2c3a7.PNG)
And other here

**Comment by renzuzu** [comment]
> This is the only error that i see ![Whatisthis](https://user-images.githubusercontent.com/65845786/201165684-ff952f7e-af89-4528-a6ec-2543dbaa7267.PNG)

yes someone already pushed an update on this im waiting for a fix a its conflicted.

**Comment by Gameadictive** [comment]
I would love your renzu_garage and renzu_vehicleshop update for make it all working perfectly <3

**Comment by Gameadictive** [comment]
Renzu, is still a bug when you take out a car from garage and get in, when you try to get again, the same visual error, gives you the key in case you dont have but car is not spawning cause think the car is out.
