### ISSUE TITLE
Duplication of realistic park cars?

### ISSUE THREAD

**Issue by Gameadictive** [renzuzu/renzu_garage#302]
![image](https://user-images.githubusercontent.com/65845786/200327167-fc796439-c531-4da9-9e06-b7683bb88ee7.png)

**Comment by renzuzu** [comment]
this is weird, is this upon spawning ?
its odd to duplicate it when theres a 
```
if spawned_cars[park.plate] == nil then
```
the value from spawned_cars[park.plate]  will be the entity id.

unless this vehicle become a network for unknown reason.

whats your game build version so i could test?

**Comment by Gameadictive** [comment]
The version is 5963 and esx legacy 1.8.5 it just happens when somebody reconnect to the server after a while it comes normal.
