### ISSUE TITLE
[BUG] Main Branch Keys Items Version [LOCKPICK]

### ISSUE THREAD

**Issue by Gameadictive** [renzuzu/renzu_garage#303]
Well /lockpick and item lockpick not working.

As hotwire in general for some reason.

**Comment by renzuzu** [comment]
i havent tried lockpick command for a long time..

did you try a lockpick item?

**Comment by Gameadictive** [comment]
Yes i got a item called lock pick. But is not like the key one it has no function from your renzu_garage maybe is something with that?

**Comment by renzuzu** [comment]
there is a register item for lockpick. 
if there is other lockpick registered item from other resource this might conflict with it

**Comment by Gameadictive** [comment]
Where is your lockpick item function? I didn´t see in readme.

**Comment by Gameadictive** [comment]
But i see i have some other resource using the lockpick system ... oh sht... Is the jobcreator but anyway maybe do something with the lockpick system a rework to be an easy configure thing or something would be great.

**Comment by Gameadictive** [comment]
![esx_job](https://user-images.githubusercontent.com/65845786/200618826-c278f372-06d2-42d2-bd6f-f79d3a54f7e0.PNG)
This is the code from the esx_job_creator

**Comment by Gameadictive** [comment]
How is the hud uy from your code? my client is prompting like 2, one with a circle and under a progressbar. Your is the circle one?

**Comment by Gameadictive** [comment]
Yep i see trough all my scripts and codes there are like 3 or 4 different lock pick codes for heist is one for esx_job_creator is other for esx_policejob is other and for yours is other

**Comment by Gameadictive** [comment]
Oh its your hud for lockpick system ok

**Comment by Gameadictive** [comment]
I must redo my own all lockpick codes from all and i suppose i must do it with yours some export lockpick
