### ISSUE TITLE
Native error

### ISSUE THREAD

**Issue by LichuTek** [renzuzu/renzu_garage#307]
![image](https://user-images.githubusercontent.com/89167678/201232340-ccf511b9-3620-42d4-aa3c-1946a4ef6ee0.png)

Another problem I have is that I get this error:

Failed load @renzushield/ini.lua 

Maybe it's something I missed reading, in that case sorry for the inconvenience

**Comment by Gameadictive** [comment]
I got that error too.

**Comment by Gameadictive** [comment]
About the renzushield
