### ISSUE TITLE
what is renzu_shield?

### ISSUE THREAD

**Issue by troner14** [renzuzu/renzu_garage#310]
When the renzu_garage starts, this comes out, what does it represent?

![image](https://user-images.githubusercontent.com/73949396/201978173-09599482-89a0-4678-bc4b-3e1ce9317979.png)

**Comment by renzuzu** [comment]
you can ignore it, or remove it fxmanifest.

**Comment by troner14** [comment]
I'm curious, can I know what it is?

**Comment by renzuzu** [comment]
Its protects events, blocked unregistered explosions and entity, and probably blocked new resource being injected.

I planned to release it but im still fixing issue
I dont want the public to use a wip AC.
