### ISSUE TITLE
About Impound

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_garage#311]
Pag nag iimpound di sya napasok agad sa list ng impound exmaple sa mrpd impound ko sya inimpound wala sya nalabas na notif is eto >>
![image](https://user-images.githubusercontent.com/105653892/202533655-66620ea1-727f-4c75-a956-013a4bfa7878.png)

then pag chineck ko sya sa garage once na clinick ko yung TAKE OUT mag nnotif na naka impound

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_garage/commit/4523064e43deffaf07efb54b8c993f0683678e39

possible issue

**Comment by razeraze** [comment]
thanks tito renz
