### ISSUE TITLE
Getting this issue Qb

### ISSUE THREAD

**Issue by Wackogaming** [renzuzu/renzu_garage#314]
![image](https://user-images.githubusercontent.com/100019533/202899334-bfc65b4a-0e49-43eb-9979-dfe9fe8bcf0a.jpeg)

**Comment by renzuzu** [comment]
this is fixes on latest branch

last commit disable the ox_lib config if ox_inventory is missing/non started

take note ox_lib is required in this resource
its better instead having my other resource like notify, menu, popui
