### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Im-Kayun** [renzuzu/renzu_garage#316]
When a player enters a garage and then leaves the server, when he enters there is no way out. Would there be a possibility to check if he is in a garage and add the option to exit?
From 0:12 to 2 minutes is the fivem opening, you can skip that part.
https://streamable.com/da39xc

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_garage/commit/aa1c572357b9e71b36e32a3a3a2cb03318186df0

this allowed player to turnback to safecoords outside of private garage. if they quit inside of privategarage

**Comment by Im-Kayun** [comment]
I did some testing here, and when I enter the public garage and exit the server, the next time I spawn I will die of a fall and end up in my garage. I also noticed that the markers and drawtext keep blinking.
https://streamable.com/qzbrqj

**Comment by renzuzu** [comment]
i did some workaround for goto garage. but i really dont know if this will be good if theres a spawn manager script like qb-spawn logic (spawn triggering from playerdata coords) if spawn manager script dont retrigger setentitycoords (on same location) . this will work

**Comment by Im-Kayun** [comment]
I am having some problems testing the garage probably because vehicleshop is giving a database error, I have already opened issue in the other repository. Now I was looking how to share the garage keys and I think it doesn't make sense in the list to share the keys of all garages including the ones we don't own or don't have permission. Regarding the player entering the server and dying from fall damage, at least in qb it is solved
![image](https://user-images.githubusercontent.com/84230221/203137970-ec9ed699-3789-43ea-9016-157311b6e147.png)
