### ISSUE TITLE
vehicle is not starting

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_garage#319]
vehicle is not starting i buy it in the vehicleshop then ill try to drop the key but it is not starting. Then ill try again to get the key vehicle still not starting, and i try garage vehicle and i try to get out of the car to test if the key was still in the inventory and tried to go back to the car but to make sure its going to start but it wasn't

**Comment by renzuzu** [comment]
is your vehicle shop is the normal pdm?

its in the config

```
Config.VehicleShopCoord = {
    [1] = vec3(-35.65,-1095.9,26.4), --x , y, z
} --x,y,z of the current vehicle shop
```

make sure you dont use any other vehicle keys it could conflict

**Comment by razeraze** [comment]
i used latest renzu_shops

**Comment by razeraze** [comment]
before i use the latest version i already use the old version of renzu_garage, i try now its working

**Comment by UHDFreddyEST** [comment]
Hy,

 I also have problems. Before i make a server restart, i can:
1) Store vehicles to garages and take them out
2) Park, lock and unlock them
3) Start engine

After server restart comes problems.
1) take out vehicle from garage, exit the vehicle and cand lock them. engine wont start etc.
2) vehicle what parked outside cant unlock them. 
basecly says no ownable vehicle.

in database its shows i'm the owner. but still cant lock, unlock or start engine. like ewery restart i lost keys,

i use final ESX Legacy 1.8.5, your final vehicleshop v1Final, and final your garage v1.824, also have ox_ installed.

**Comment by renzuzu** [comment]
hi the system uses keys, if you dont have it on your inventory, you wont have access. assuming your using ox_inventory

**Comment by ELFAQC** [comment]
thx
