### ISSUE TITLE
Garage error don't how to solve

### ISSUE THREAD

**Issue by CengizKocer** [renzuzu/renzu_garage#320]
Hi this is the issue i get each time i buy the car by using renzu_vehicleshop that works smooth.
Realistic parking works smooth also untill i park then i take out vehicle( sometimes also this does not work).

Here i made a screenshot.
![image](https://user-images.githubusercontent.com/6495759/205818472-f073d356-690c-4987-b7ea-14a2f21dff72.png)

**Comment by renzuzu** [comment]
post a reproduction steps how you produce the error..

i assume isince this is ox_ivnentory error. you might no install keys item?

**Comment by CengizKocer** [comment]
Hey this is the next error i get bro 😕

[cid:3c8572ec-a048-432a-b087-d46ecfbbcfba]
________________________________
Van: renzuzu ***@***.***>
Verzonden: dinsdag 6 december 2022 06:17
Aan: renzuzu/renzu_garage ***@***.***>
CC: CengizKocer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [renzuzu/renzu_garage] Garage error don't how to solve (Issue #320)


post a reproduction steps how you produce the error..

i assume isince this is ox_ivnentory error. you might no install keys item?

**Comment by renzuzu** [comment]
install missing sql columns, you probably dont have `type` column in owned_vehicles

**Comment by renzuzu** [comment]
you could say here what you want.
