### ISSUE TITLE
Config.PrivateHousingGarageEnable = false does not work

### ISSUE THREAD

**Issue by TheFlyBandit** [renzuzu/renzu_garage#323]
When set to false housing garages still use the private garages instead of quick menu

**Comment by TheFlyBandit** [comment]
and neither does 

Config.Private_Garage = false -- Enable Private Garage system


I have it set like this and the private garages are still there

**Comment by renzuzu** [comment]
there is no way to use quick menu in housing garage as for now..
it was supported last time, but got remove

you could still manually support it for a while

```
TriggerEvent('renzu_garage:property',garageid, garagecoord, garagespawn)
```

garagespawn is vec4

**Comment by TheFlyBandit** [comment]
I have managed to get the private garages working with housing and valet with your new export for removing cars from private garages so I no longer need the quick menu for housing 👍
