### ISSUE TITLE
NPC Vehicles can still be stolen even with lock system turned on.

### ISSUE THREAD

**Issue by TheFlyBandit** [renzuzu/renzu_garage#326]
When the lock system is on I am able to walk up to NPCs and pull them out of the car. Is it suppose to be like this? If so would you be able to make it more like other key scripts where you can't pull the NPCs out of cars and instead have to point a gun at them for them to give you the keys?

**Comment by renzuzu** [comment]
i have pushed yesterday regarding some lock system.. you could test it.

**Comment by TheFlyBandit** [comment]
I do not see any commits about adding or changing the lock system? I am using the version that has the remove car from private garage export.

**Comment by renzuzu** [comment]
i do have updates in keys client and server

**Comment by TheFlyBandit** [comment]
I must be blind then because I am not seeing it. The only Key Commits I see are for newly purchased vehicles and for serial numbers. I don't see anything else. This is what I can see from past 6 days. 
![Screenshot 2022-12-12 125305](https://user-images.githubusercontent.com/102429379/207118624-4e3c07e6-60b0-41ce-b6a7-884b0659e5bb.png) What am I missing?

**Comment by TheFlyBandit** [comment]
Yes, you said it was yesterday when you first commented so I figured it would be a recent commit no?

**Comment by TheFlyBandit** [comment]
So I just tested most recent version of the script and I can still steal NPC driven cars by just walking up and pulling them out so it does not appear anything has changed there.
