### ISSUE TITLE
More Suggestions

### ISSUE THREAD

**Issue by Im-Kayun** [renzuzu/renzu_garage#329]
Replace all information that is saved in KVP to be saved in database.

When the car is saved, save the deformations. - https://github.com/Kiminaze/VehicleDeformation

**Comment by renzuzu** [comment]
its already saved deformation.

more database more error and problem from users.

which feature are you suggesting to use a database?

**Comment by Im-Kayun** [comment]
I saw that you store the fakeplates, keyserials and VehiclePersistentData in kvp. I am not very familiar with seeing and using this and I am afraid that this data will be lost if the player formats the computer or deletes something they should not.

**Comment by renzuzu** [comment]
no , kvp in client store in fivem folder
however kvp in server store in 
/txdata/folder/db
or its near on cache folder on server files
