### ISSUE TITLE
Problem with renzu_garage

### ISSUE THREAD

**Issue by LichuTek** [renzuzu/renzu_garage#330]
Hello, I have a problem and it is that I download renzu_garaje release 1.83 and when I buy a vehicle with esx_vehicleshop, it does not give me the keys and when I store it in a garage it tells me that the vehicle is not mine, and the sql tables are loaded fine, I have ox_inventory in its latest version and add the keys to the items

**Comment by renzuzu** [comment]
>when I buy a vehicle with esx_vehicleshop
> it tells me that the vehicle is not mine

probably incompatiblity issue with esx_vehicleshop in plate formats

**Comment by LichuTek** [comment]
> 

Thanks for taking the time to answer, your scripts are very complete and you are looking for what is missing in the free scripts community. Having said this, I wanted to ask you if renzu_vehicleshop is compatible?

**Comment by renzuzu** [comment]
yes but, i stopped working on the vehicle shop now, as renzu_shops offer complete shop solution including vehicleshop.
