### ISSUE TITLE
boolean

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_garage#333]
how to fix this
![image](https://user-images.githubusercontent.com/105653892/207400955-d77ee98d-412c-4ac5-8977-626b19b324c8.png)

**Comment by raaazeee** [comment]
i already download the latest version of renzu garage but when i check f8 i saw error

**Comment by Slewog** [comment]
Hey find this function in u script and copy the line 253  i added this, it's working for me ;) 
![image](https://user-images.githubusercontent.com/31140215/214077091-46b1130f-087e-4323-b00b-823fc8ab324f.png)
