### ISSUE TITLE
I cannot start my engine entering vehicle

### ISSUE THREAD

**Issue by TerinShells** [renzuzu/renzu_garage#343]
Hi, my problem is that when i spawn car, the vehicle work fine but when I re-enter in, the engine don't want to start. How can I fix it ?

**Comment by TerinShells** [comment]
C’est bon pour moi !

Le mer. 8 mars 2023 à 3:05 p.m., renzuzu ***@***.***> a
écrit :

**Comment by renzuzu** [comment]
You dont have keys in inventory
Register them
