### ISSUE TITLE
Searching for carkeys in stolen vehicles 

### ISSUE THREAD

**Issue by mixmax510** [renzuzu/renzu_garage#350]
Hi so im currently using some of your scripts and on my previous car key system i was able to steal npc vehicles and search for carkeys in them by registering the nui for the U key i am curious if you could add such thing in your scripts i can give you the sourcecode ive been using if u want to ;)) if not i will have to redo your script but i feel you will have more ease adding it yourself oh and i alsoe have a turn off engine system in the script

**Comment by renzuzu** [comment]
the logic on the key system here, is when you lockpick a vehicle you automatically get the keys by hotwiring it.
