### ISSUE TITLE
any update 

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_garage#352]
![image](https://user-images.githubusercontent.com/105653892/211231193-0c46d481-e12b-43fe-9bd6-e010790b5440.png)

**Comment by Slewog** [comment]
Hey a have the same error and i finded a fix, the problem when u spawn, ox_lib send a bool set to false, maybe not the best but is working : `if not value then return end`

![image](https://user-images.githubusercontent.com/31140215/214075876-9ea094bc-f004-4936-b53b-af7b392f6858.png)

**Comment by DevMinkh** [comment]
i have try it this way and atm no more errors

`lib.onCache('vehicle', function(value)
    SetPedConfigFlag(cache.ped,429,false)
    if value then
        local ent = Entity(value).state
        if ent.havekeys and not GetIsVehicleEngineRunning(value) and not IsVehicleNeedsToBeHotwired(value) then
            SetPedConfigFlag(cache.ped,429,false)
            SetVehicleNeedsToBeHotwired(value,false)
            SetVehicleEngineOn(value,true,true,false)
            SetVehicleJetEngineOn(value,true)
            Wait(100)
            SetPedConfigFlag(cache.ped,429,false)
        end
    end
end)`

**Comment by Slewog** [comment]
> i have try it this way and atm no more errors
> 
> `lib.onCache('vehicle', function(value) SetPedConfigFlag(cache.ped,429,false) if value then local ent = Entity(value).state if ent.havekeys and not GetIsVehicleEngineRunning(value) and not IsVehicleNeedsToBeHotwired(value) then SetPedConfigFlag(cache.ped,429,false) SetVehicleNeedsToBeHotwired(value,false) SetVehicleEngineOn(value,true,true,false) SetVehicleJetEngineOn(value,true) Wait(100) SetPedConfigFlag(cache.ped,429,false) end end end)`

Can u add a screenshot or format the please, it's very easy to read like this x)

**Comment by DevMinkh** [comment]
![image](https://user-images.githubusercontent.com/39908861/214078348-6bc8c36a-8ca8-450e-8694-bf133bd38cf2.png)

**Comment by Slewog** [comment]
Thank you, ok u did +/- the some of me but i think this line need to be inside the if too no?
`SetPedConfigFlag(cache.ped,429,false)`

**Comment by Slewog** [comment]
Ok thank you

**Comment by renzuzu** [comment]
forgive me for taking too long to fix this little error.

**Comment by DevMinkh** [comment]
no problem, your work is to good to say anything on a time value.

LG
