### ISSUE TITLE
"boolean value" fault

### ISSUE THREAD

**Issue by Paulewas** [renzuzu/renzu_garage#364]
Hello.

I got this fault and cant fix it. I do not understand what is wrong..

![1](https://user-images.githubusercontent.com/124680933/217243079-bf1e2094-20fb-47bd-88b9-e12e20f18fb7.png)
![2](https://user-images.githubusercontent.com/124680933/217243110-57cfd145-0723-4ae1-b4b6-11b0a2024001.png)
![3](https://user-images.githubusercontent.com/124680933/217243128-e3ebca2c-5197-4fff-856c-58e3643a1cd6.png)
![4](https://user-images.githubusercontent.com/124680933/217243141-60aa208e-7817-41b7-8a00-4ae7aef2d85a.png)

**Comment by renzuzu** [comment]
forgive me for taking too long to fix this little error.

**Comment by Paulewas** [comment]
To long? You are faster than lightning. Grateful :)

**Comment by Paulewas** [comment]
Now have another fault, and garage not give me key then I buy vehicle..
![1](https://user-images.githubusercontent.com/124680933/217261319-847e04d3-aa74-4bca-99f6-b75232b72702.png)
![2](https://user-images.githubusercontent.com/124680933/217261340-7fd9cf1b-424a-431a-b107-72d946dc28dc.png)
![3](https://user-images.githubusercontent.com/124680933/217261371-29b5a723-9d55-42d4-89ba-905737a24161.png)
![4](https://user-images.githubusercontent.com/124680933/217261383-4031d116-54a3-4e4f-a0f3-8d0011574e51.png)

**Comment by renzuzu** [comment]
> Now have another fault, and garage not give me key then I buy vehicle.. ![1](https://user-images.githubusercontent.com/124680933/217261319-847e04d3-aa74-4bca-99f6-b75232b72702.png) ![2](https://user-images.githubusercontent.com/124680933/217261340-7fd9cf1b-424a-431a-b107-72d946dc28dc.png) ![3](https://user-images.githubusercontent.com/124680933/217261371-29b5a723-9d55-42d4-89ba-905737a24161.png) ![4](https://user-images.githubusercontent.com/124680933/217261383-4031d116-54a3-4e4f-a0f3-8d0011574e51.png)

this error must be thrown if keys is not registered in ox_inventory.
