### ISSUE TITLE
ERROR CUSTOM COLORS 

### ISSUE THREAD

**Issue by HazeBeats** [renzuzu/renzu_garage#374]
Hello, when you store a vehicle in the garage, it is no longer possible to modify its color at the mechanic. Anyone have this fix? Thanks

**Comment by HazeBeats** [comment]
Would it be possible to have a screen of the line to delete? THANKS

**Comment by HazeBeats** [comment]
Should the lines be deleted?
![Uploading Capture d’écran 2023-02-17 135319.png…]()

**Comment by renzuzu** [comment]
the custom colors (rgb) are always priority in GTA codebase
