### ISSUE TITLE
Need a little help with keys.lua and maybe export with changing plates

### ISSUE THREAD

**Issue by silez** [renzuzu/renzu_garage#376]
Hello renzuzu :)

First of all, thank you for the great garage!

I have a small mistake here. Getting in and out of a parking space is no problem, but it still throws this error in the console every time:
![Screenshot_20230217_181017](https://user-images.githubusercontent.com/8078098/219720377-b62641c7-b5d7-4696-82a3-b47f00852472.png)
This seems to be something with the caching of ox_lib - I think. But i' am not shure 😁

And the other question would be, is there an export that when changing the license plate also changes the license plate in the "vehicle" column of "owned_vehicles"?

I have already used your export `exports.renzu_garage:GiveVehicleKey(newPlate,source)` to put the new car key in my inventory after changing the license plate, but then you can no longer park the car in a garage because it no longer belongs to the player. This is because the license plate in the "vehicle" column is not changed.

If I change the license plate to "TEST1234", the "plate" column in "owned_vehicles changes but not in the "vehicles" column.
For testing, I changed the "plate" part in "vehicle" column to `"plate":"TEST1234",` directly in the database and after that, the vehicle can be parked again.

Is there a "simple" solution? Maybe an export or does it have to be solved differently?
Since I'm not a die-hard lua programmer, I wanted to ask here.

Thank you for any help

**Comment by silez** [comment]
> [f0a0052](https://github.com/renzuzu/renzu_garage/commit/f0a0052a501c00dce12aaa2fb0b06e837060f7a1)

Okay that was fast :)
Thank you :)

Only the plate change would be great to fixed :D

**Comment by renzuzu** [comment]
do you mean the vehicles column from owned_vehicles right?

whats the purpose of this?
you gave special plate for player? ex. donator.
there is no function in garage that support this yet.

you can do a workaround by using the fake plate changer, this is persistent even if newly restarted server.

**Comment by silez** [comment]
> do you mean the vehicles column from owned_vehicles right?

Yes :)

> whats the purpose of this? you gave special plate for player? ex. donator. there is no function in garage that support this yet.

Exactly either that or you buy a license plate (from a mechanic or in the shop, actually it doesn't matter where xD), for example, and then want to change it, but not as a "fake plate" but really completely in the system, so that the police can also determine the right owner when checking the license plate, because the vehicle owner can no longer do this with a fake plate be determined (at least that's how it is for me)
Of course, that could also be used well, for me both would be very good, which is why I also have a script to change the license plate. On the one hand, the fakeplate can be very good for a bad fraction if you want to start an action, on the other hand, someone wants to change their license plate without starting an extra "bad" action


> you can do a workaround by using the fake plate changer, this is persistent even if newly restarted server.

That's exactly what I found out. It's also a great system, but I think an export for "fixed" changing the license plate could be interesting for many - similar to the export where you get a new key in the inventory.


For example, this is the ServerEvent with which I change the license plate. There I already have an export with your new key in it:

```
RegisterServerEvent('dCarPlate:RemovePlate', function(oldPlate, newPlate, vehicleProps)
    local count = exports.ox_inventory:Search(source, 'count', Config.CarPlateItem)
    if count <= 0 then return end
    local xPlayer = ESX.GetPlayerFromId(source)
        if Config.UpdateOwnedVehicles then
            MySQL.Async.execute('UPDATE owned_vehicles SET plate = @newPlate WHERE plate = @oldPlate', {
                ['@oldPlate'] = oldPlate,
                ['@newPlate'] = newPlate,
            })
        end
    exports.ox_inventory:RemoveItem(source, Config.CarPlateItem, 1)
    exports.renzu_garage:GiveVehicleKey(newPlate, source)

    sendToDiscord(9196287, 'Kennzeichen', xPlayer.getName().." hat sein Fahrzeugkennzeichen gewechselt, altes Kennzeichen:  **"..oldPlate.."** \n\n neuen Kennzeichen: **"..newPlate.."**\n\nFahrzeug: "..vehicleProps.name , 'XenonRP')

end)
```

There, with another export, the license plate (name/number) could also be inserted in the vehicles column of owned_vehicles, right?

But maybe I'm just too stupid to write my own function that only updates the part with `"plate":"TEST1234",` hahaha 🤣🤣

**Comment by renzuzu** [comment]
> RegisterServerEvent('dCarPlate:RemovePlate', function(oldPlate, newPlate, vehicleProps)
>     local count = exports.ox_inventory:Search(source, 'count', Config.CarPlateItem)
>     if count <= 0 then return end
>     local xPlayer = ESX.GetPlayerFromId(source)
>         if Config.UpdateOwnedVehicles then
>             MySQL.Async.execute('UPDATE owned_vehicles SET plate = @newPlate WHERE plate = @oldPlate', {
>                 ['@oldPlate'] = oldPlate,
>                 ['@newPlate'] = newPlate,
>             })
>         end
>     exports.ox_inventory:RemoveItem(source, Config.CarPlateItem, 1)
>     exports.renzu_garage:GiveVehicleKey(newPlate, source)
> 
>     sendToDiscord(9196287, 'Kennzeichen', xPlayer.getName().." hat sein Fahrzeugkennzeichen gewechselt, altes Kennzeichen:  **"..oldPlate.."** \n\n neuen Kennzeichen: **"..newPlate.."**\n\nFahrzeug: "..vehicleProps.name , 'XenonRP')
> 
> end)

since you already have the snippet to change the plate

why not add there to change the vehicle column?

this feature can be add in garage. but not right now, im currently busy atm.

because if its only 1 framework, this is easy to add, now i have to test two framework to add the feature.

now you can modify this like this

```
RegisterServerEvent('dCarPlate:RemovePlate', function(oldPlate, newPlate, vehicleProps)
    local count = exports.ox_inventory:Search(source, 'count', Config.CarPlateItem)
    if count <= 0 then return end
    local xPlayer = ESX.GetPlayerFromId(source)
    local scalar = MySQL.scalar.await('SELECT vehicle FROM owned_vehicles WHERE plate = ?', {oldPlate})
    local vehicle = json.decode(scalar[1]).plate = newPlate
   local update = MySQL.update.await('UPDATE owned_vehicles SET vehicle = ? WHERE plate = ?', {json.encode(vehicle), oldPlate})

        if Config.UpdateOwnedVehicles then
            MySQL.Async.execute('UPDATE owned_vehicles SET plate = @newPlate WHERE plate = @oldPlate', {
                ['@oldPlate'] = oldPlate,
                ['@newPlate'] = newPlate,
            })
        end
    exports.ox_inventory:RemoveItem(source, Config.CarPlateItem, 1)
    exports.renzu_garage:GiveVehicleKey(newPlate, source)

    sendToDiscord(9196287, 'Kennzeichen', xPlayer.getName().." hat sein Fahrzeugkennzeichen gewechselt, altes Kennzeichen:  **"..oldPlate.."** \n\n neuen Kennzeichen: **"..newPlate.."**\n\nFahrzeug: "..vehicleProps.name , 'XenonRP')

end)
```

assuming your using ox mysql.
not sure if this wont throw error i havent tried, but this is how its should do.
dont forget to change the plate in client too

**Comment by silez** [comment]
> since you already have the snippet to change the plate
> why not add there to change the vehicle column?

Because I've only been learning Lua for a few weeks, I didn't know how to implement the json change in Lua and then set the new plate in the vehicles column

> this feature can be add in garage. but not right now, im currently busy atm.

That's completely fine, I've seen that you have opened new github projects and that you "have to" test for several frameworks is clear to me, that's why I have so much respect for it

> because if its only 1 framework, this is easy to add, now i have to test two framework to add the feature.
> 
> now you can modify this like this
> 
> ```
> RegisterServerEvent('dCarPlate:RemovePlate', function(oldPlate, newPlate, vehicleProps)
>     local count = exports.ox_inventory:Search(source, 'count', Config.CarPlateItem)
>     if count <= 0 then return end
>     local xPlayer = ESX.GetPlayerFromId(source)
>     local scalar = MySQL.scalar.await('SELECT vehicle FROM owned_vehicles WHERE plate = ?', {oldPlate})
>     local vehicle = json.decode(scalar[1]).plate = newPlate
>    local update = MySQL.update.await('UPDATE owned_vehicles SET vehicle = ? WHERE plate = ?', {json.encode(vehicle), oldPlate})
> 
>         if Config.UpdateOwnedVehicles then
>             MySQL.Async.execute('UPDATE owned_vehicles SET plate = @newPlate WHERE plate = @oldPlate', {
>                 ['@oldPlate'] = oldPlate,
>                 ['@newPlate'] = newPlate,
>             })
>         end
>     exports.ox_inventory:RemoveItem(source, Config.CarPlateItem, 1)
>     exports.renzu_garage:GiveVehicleKey(newPlate, source)
> 
>     sendToDiscord(9196287, 'Kennzeichen', xPlayer.getName().." hat sein Fahrzeugkennzeichen gewechselt, altes Kennzeichen:  **"..oldPlate.."** \n\n neuen Kennzeichen: **"..newPlate.."**\n\nFahrzeug: "..vehicleProps.name , 'XenonRP')
> 
> end)
> ```
> 
> assuming your using ox mysql. not sure if this wont throw error i havent tried, but this is how its should do. dont forget to change the plate in client too

Thank you very much for the snippet. I'll try it right now and see if it works.
In the client I already have a function to change the license plate.
