### ISSUE TITLE
[BUG] if fine not written, it will still stay as impounded

### ISSUE THREAD

**Issue by xrtw** [renzuzu/renzu_garage#378]
if fine not written and stays in impound_garage sql as "fine":"", you can not take, it will return back to impound

**Comment by renzuzu** [comment]
sorry for late replied, 
it seems i cant reproduce this

i impound the vehicle
set duration
reason
no fine amount

i still can get the vehicle from impound

**Comment by renzuzu** [comment]
i will leave this as low priority, as this does not affect the impound at all right? it just stay on the database..

**Comment by renzuzu** [comment]
oh i see its a shit bug,
but i know the logic in impound is if impound is set to 1 from database owned_vehicles, it will show to impound list and show impounded in normal garage.

the purpose of database is for information in leftside.

if you experience the vehicle always impounded after you pull out from impound ,it could be the impound column is not setting to 0

**Comment by renzuzu** [comment]
i tested this it seems its removed the data from database.
