### ISSUE TITLE
This turn off automatic engine start

### ISSUE THREAD

**Issue by SchwarzerMercedes** [renzuzu/renzu_garage#379]
Hi, how can i turn on automatic engine start.

**Comment by Pilotodev** [comment]
I have the same problem... When you spam a car and get out of it, when you get in the car it doesn't start. I dont know how to fix that... And I have a second problem, when I spawn a car by /car ... example; /car blista, it disappears when I spam another car, so if I spam two cars one always disappears.

**Comment by renzuzu** [comment]
if the issue is the same with Piloto, which is not using ox_inventory
theres a fix for that.
https://github.com/renzuzu/renzu_garage/commit/316d3e4bf0b4ecf6127a236c8733835d94d408b3
