### ISSUE TITLE
Hi!! I have two problems that I cant see the solution.

### ISSUE THREAD

**Issue by Pilotodev** [renzuzu/renzu_garage#381]
When you spam a car and get out of it, when you get in the car it doesn't start. I dont know how to fix that... And I have a second problem, when I spawn a car by /car ... example; /car blista, it disappears when I spam another car, so if I spam two cars one always disappears.

**Comment by renzuzu** [comment]
did you have keys item in ox_inventory?

**Comment by Pilotodev** [comment]
Emm... I dont use ox_inventory. I use redesigned inventory default, but the problem is when I spawn a car by administrations command /car.

**Comment by Pilotodev** [comment]
I Installed ox inventory but I have the same problem renzu... When you get out of the car and get back in the car it stays off. And I have another problem more, when you park a car with /park or /parkigmeter the car disappears.

**Comment by Pilotodev** [comment]
Before having the ox inventory, it didn't happen that the car disappeared.

**Comment by renzuzu** [comment]
> I have another problem more, when you park a car with /park or /parkigmeter the car disappears.

it seems i cant reproduce your problem,
probably your parking a vehicle is not yours.

**Comment by renzuzu** [comment]
> Have not enough money so it just deletes
this good report
i will try and push and update if its confirm

**Comment by Pilotodev** [comment]
Very nice, the problem was fixed.

**Comment by Pilotodev** [comment]
One more issues hehehe. When U use a lockpick for rob a player car, the freezes started but you can't move it.

**Comment by renzuzu** [comment]
its probably right, its the /park command. currently its not stealable, but you can impound.

if you it to be stealable , please open a new issue with enhancement tag.

Thanks
