### ISSUE TITLE
problem when logging out and restarting the server

### ISSUE THREAD

**Issue by FilipeCuco** [renzuzu/renzu_garage#382]
Public Garage:
when I log off the server inside a public garage and restart the server when I log on, this happens: https://streamable.com/0qsthx

Private Garage:
same thing happens with private garages: https://streamable.com/6zg55b

**Comment by renzuzu** [comment]
this dont support saving last location if you restart the whole server
![image](https://user-images.githubusercontent.com/82306584/224198258-13ad56c5-dc9e-476a-82bd-8302fbc0b863.png)

as you can see in this line
safecoords event is being triggered when you go to private garage or Goto Garage button.
this save a cache localy, but when you restart the server the cache will be gone.
the purpose only for this is on live server when player gets disconnected.

now when you gonna restart the server, player should receive a warning to get off on the private garage, Goto Garage room.
