### ISSUE TITLE
Can buy Private Garage but don't get the key

### ISSUE THREAD

**Issue by SleepingFox25** [renzuzu/renzu_garage#386]
Hello, I have a little problem with private garages. Basically, I can buy a private garage without worries, but I don't get the keys when buying, and when I do /garagekeys manage, no garage comes out in my name, and the DB does not fill up either more.
Do you know what it could be from?

Server Version: ESX Legacy 1.8.5
Script version: 1.85
Potential errors : Nothing appear in the F8 or in the console
![garagebuyed](https://user-images.githubusercontent.com/127875904/225064893-693a8add-69e9-49bf-bd19-fe1611f03cd8.png)

![garage2](https://user-images.githubusercontent.com/127875904/225065272-c06ba8d5-961c-4c21-9d76-d4e710f3da40.png)

![garage3](https://user-images.githubusercontent.com/127875904/225065675-7cf35556-3858-4145-aace-66a7d32f54dd.png)

**Comment by renzuzu** [comment]
this garagekeys is only for public garage.

if you want to share private garage (temporary)
use /giveaccess 2 (id of player)
