### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mas7or123** [renzuzu/renzu_garage#39]
Hello bro can i dm you on discord i want to make a custom script i think you can help me with it my discord: Mr.lua# 0662

**Comment by renzuzu** [comment]
message me in CFX

**Comment by mas7or123** [comment]
Can you add me on discord is better for me i dont know how to use the cfx

**Comment by BlueSky-fur** [comment]
> Can you add me on discord is better for me i dont know how to use the cfx

you dont know how to use the fivem forums?
