### ISSUE TITLE
The impound does not show me the vehicles 

### ISSUE THREAD

**Issue by SleepingFox25** [renzuzu/renzu_garage#390]
hello, since the new version of the script, I encounter a problem with the impound, it's impossible for me to see the vehicles present inside, however it does show me the categories of vehicles, suggesting that cars are inside.

Video of the problem : https://youtu.be/R0szuU_U5CU

In others garage, I have no problems, I see jobs and privates cars, but impound isn't ok with this idea

**Comment by SleepingFox25** [comment]
![image](https://user-images.githubusercontent.com/127875904/226110014-f851cbf4-f168-4e47-9c1d-217e2dfdd41b.png)

**Comment by SleepingFox25** [comment]
![image](https://user-images.githubusercontent.com/127875904/226110240-d7112ddd-c4de-44f9-abdb-7e4b4afaa77d.png)
the davis pound, where I took the video, the data is empty, yet it shows me different categories with a number of cars in it, but the base does not seem to agree with that

**Comment by renzuzu** [comment]
how did you impound the vehicle?
did you just store pressing [E]. which i havent tested..

if you use the form and select the impound garage, its should not happen at all.

**Comment by SleepingFox25** [comment]
> 
this happens when I go to the impound to consult the vehicles present there, not when I voluntarily impound a vehicle, I specify that I see these vehicles when I have the police job and that I go to the other impound than police.

**Comment by renzuzu** [comment]
base on your 
>Video of the problem : https://youtu.be/R0szuU_U5CU

the impound data is from mrpd not in davis impound

**Comment by renzuzu** [comment]
>I'm not sure, but if you have police job, you can see all impounded cars from different locations

not really sure about this 
but this could be affecting from Unique vehicle per garage in config.
