### ISSUE TITLE
Garage menu on foot not working.

### ISSUE THREAD

**Issue by Timmy5314** [renzuzu/renzu_garage#392]
I only see the menu in cars not on foot

**Comment by renzuzu** [comment]
not actional withou more information.

re open with the require information . ex. which garage. and what menu.

**Comment by Timmy5314** [comment]
Every garage if i am close to the ped on foot I can't open press e to open menu , only if iam sitting in the car.

**Comment by renzuzu** [comment]
theres a local ped? if yes its configure to use target

**Comment by Timmy5314** [comment]
Yeah the peds that are in front of the garage i will try to use target many thanks

**Comment by Timmy5314** [comment]
Is still not appearing the small bar for the menu. I send a picture from a other issues 

![Screenshot_20230320-094008_YouTube](https://user-images.githubusercontent.com/67314632/226288445-0011e8c3-9d36-4d68-8077-e0e4abc43112.jpg)

**Comment by renzuzu** [comment]
does you resource name is renzu_garage?
without -main or other texts.

because its odd

**Comment by Timmy5314** [comment]
Yes I did, everything working only the press e bar is not working, if i am using older version 1.81 / 1.825 everything is working great only the new version with the peds.

**Comment by Timmy5314** [comment]
There are also no errors, maybe it hase something with popui is that possible?
