### ISSUE TITLE
Script Error Execution of native

### ISSUE THREAD

**Issue by SleepingFox25** [renzuzu/renzu_garage#395]
hey, I'm re-opening a ticket following an error I have in my console sometimes. The script starts, works correctly, but this error bothers me because I can't really know what it's coming from, if you can enlighten me ^^"

Server FrameWork : Esx Legacy 1.8.5
Server Version : Lastest
Artifact : Lastest
Script Version : 1.8

**Comment by SleepingFox25** [comment]
> show me what error

![err](https://user-images.githubusercontent.com/127875904/226453899-1fedbd60-e9a3-4481-b15b-0c482b34d513.png)

**Comment by SleepingFox25** [comment]
this error means that I can open a garage, see the vehicles, select one, but once selected, the HUD disappears, I have the cursor which remains on the screen, but I cannot move, and this error appears in the F8

**Comment by renzuzu** [comment]
try updating the resource and if it throws error show me again.
because the line 895 does not match in my copy anymore.

**Comment by SleepingFox25** [comment]
> try updating the resource and if it throws error show me again. because the line 895 does not match in my copy anymore.

I update the script to the version 1.9, but still have an error :
![Uploading error.png…]()

**Comment by renzuzu** [comment]
still not using the latest main branch, i cant say which error.
in my short analyze this is where player does not exist (source)
