### ISSUE TITLE
private garage 

### ISSUE THREAD

**Issue by HiTTA757** [renzuzu/renzu_garage#397]
Unable to park cars in private garage, no garagekey in management! got notify the garage was bought, able to go inside but can not store car

**Comment by HiTTA757** [comment]
![image](https://user-images.githubusercontent.com/127186414/226918085-31dfa3d4-ee55-456a-98cd-5f03d46f01f1.jpg)


F8 error I’m getting

**Comment by HiTTA757** [comment]
no i didnt modify anything on the script. still having same problem

**Comment by renzuzu** [comment]
try downloading the latest main branch. as i did not have this issue with private garage.

re open when issue still exist, its weird to have boolean for table config.
provide more information if you could
