### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by ErinDeveloping** [renzuzu/renzu_garage#398]
Just started to use this garage script but my vehicleshop needs to add the key when you buy the vehicle and I can't figurate what trigger I should use for this or if you could integrate and make a pr for this 
https://github.com/emfan-scripts/emfan-framework/blob/main/client/cl_functions.lua (This resource is needed for my vehicleshop resource)

**Comment by ErinDeveloping** [comment]
Or if I just should keep qb-vehiclekeys?

**Comment by renzuzu** [comment]
```
from server
TriggerClientEvent('renzu_garage:SetVehicleOwner',source,plate,false) -- @plate @temporary?
from client
TriggerEvent('renzu_garage:SetVehicleOwner',plate,false) -- @plate @temporary?

```

**Comment by ErinDeveloping** [comment]
Thanks
