### ISSUE TITLE
{doubts} ox-target/garage

### ISSUE THREAD

**Issue by bbeckann** [renzuzu/renzu_garage#401]
I would like to disable peds , at the moment I am using ox-target ... I would like to disable peds and leave only the floatingtext

**Comment by bbeckann** [comment]
obrigado , outra duvida que tenho e em relação a imagem (imgs) eu gostaria de mudar o formato para png .. porem ele não aceita .. apenas jpg

**Comment by renzuzu** [comment]
for vehicles? this is intended for smaller size of resource

**Comment by renzuzu** [comment]
continuing the issue, the workaround on this is to modify the JS or html
