### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by Florian306** [renzuzu/renzu_garage#404]
![image](https://user-images.githubusercontent.com/107804876/227616622-9f01d983-c2c6-4d7a-9163-20f5b74e684f.png)
I have this issue. And I can´t open the ui

**Comment by renzuzu** [comment]
install the requires column its included in the resource file .sql

**Comment by Florian306** [comment]
![image](https://user-images.githubusercontent.com/107804876/227621788-2bc7b75f-959a-4937-8bbd-494d8e0060c8.png)
that is my owned_vehicles table

**Comment by Florian306** [comment]
The vehicles are not entered in the owned vehicle table.

**Comment by renzuzu** [comment]
the error already said the issue.. garage_id is not existing..

**Comment by Florian306** [comment]
Yeah but you see in the picture above, the garge id was in the owned_vehicle table exsist.

**Comment by renzuzu** [comment]
did you solved this?
its kinda weird when garage_id is existing but its throwing error for missing column.

check if your actually using the same database name with the one your checking with garage_id column.

**Comment by renzuzu** [comment]
re open if issue still exist
