### ISSUE TITLE
Store job vehicle & /impound dosen't work

### ISSUE THREAD

**Issue by StableBarcodeDev** [renzuzu/renzu_garage#407]
When i am trying to store a job owned vehicle that i have bought it says
you don't own this vehicle.

The only error that appears  is this at txadmin:
[ script:renzu_garage] SCRIPT ERROR: @renzu_garage/server/keys.lua:199: attempt to index a nil value (local 'props')
[ script:renzu_garage] > handler (@renzu_garage/server/keys.lua:199)

also got this:
[  script:es_extended] > TriggerServerCallback (@es_extended/server/functions.lua:172)
[  script:es_extended] > handler (@es_extended/server/common.lua:122)
[  script:es_extended] > <unknown> (@oxmysql/dist/build.js:22252)
[  script:es_extended] > runMicrotasks (<anonymous>:0)
[  script:es_extended] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by renzuzu** [comment]
i fixed the error from keys.lua which is from old features that i have removed.

about the job owned vehicle that you cannot store.

maybe your storing a temporary vehicle from Default in police garage.

**Comment by StableBarcodeDev** [comment]
about the job vehicle.  i have bought it using your vehicleshop system. It isn't supposed to work like this?
