### ISSUE TITLE
When using the Tuners error code is received

### ISSUE THREAD

**Issue by Baksteen1991** [renzuzu/renzu_garage#408]
Hi,

When trying to use the upgrade vehicle selection for your tuners script I get the following error: @renzu_garage/client/keys.lua:255: attempt to index a boolean value

**Comment by Baksteen1991** [comment]
HI, sorry to bother any indication of what the issue could be?

**Comment by renzuzu** [comment]
>@renzu_garage/client/keys.lua:255: attempt to index a boolean value


this is existing on older version AFAIK.
