### ISSUE TITLE
When picking up the car from the garage, it keeps loading, and an error is reported in the background

### ISSUE THREAD

**Issue by azm-T** [renzuzu/renzu_garage#412]
[ script:renzu_garage] SCRIPT ERROR: @renzu_garage/server/keys.lua:398: attempt to index a nil value (local 'tempvehicles')
[ script:renzu_garage] > <unknown> (@oxmysql/dist/build.js:22234)
[ script:renzu_garage] > processTicksAndRejections (node:internal/process/task_queues:96)
[ script:renzu_garage] > async rawQuery (@oxmysql/dist/build.js:22224)
[ script:renzu_garage] SCRIPT ERROR: @renzu_garage/server/server.lua:12: attempt to call a nil value (global 'CreateVehicleServerSetter')
[ script:renzu_garage] > callbackResponse (@ox_lib/callback/server.lua:59)
[ script:renzu_garage] > handler (@ox_lib/callback/server.lua:75)
[ script:renzu_garage]

**Comment by renzuzu** [comment]
any steps to reproduce this?
currently this is not actionable since no information
