### ISSUE TITLE
Hey Renzu, Good Day!!

### ISSUE THREAD

**Issue by Pilotodev** [renzuzu/renzu_garage#413]
I recently purchased Quasar inventory, is there a way to make it compatible with vehicle keys?

**Comment by Pilotodev** [comment]
Another thing, I changed the server and when migrating the data to the new server this appears, do you know how to fix it?

**Comment by renzuzu** [comment]
sorry brother no offense but i would only support open source inventory.

as this is open source you can check how its managing the key items in server/keys.lua /client/keys.lua
