### ISSUE TITLE
[Bug]  car painting with esx_lscustom and this garage

### ISSUE THREAD

**Issue by Bobsukka** [renzuzu/renzu_garage#420]
Hello got kinda big bug and thought its allready fixed but no.. so problem is when you paint car and then save it to garage and try again paint you cant anymore change that car color... and that is fcking big problem to people ho dont wana use renzucustom :D its ugly

**Comment by Bobsukka** [comment]
Awesome! it worked perfectly now!

**Comment by renzuzu** [comment]
> fcking big problem to people ho dont wana use renzucustom :D its ugly

then show me a free one that is better in my customs resource?

you dont need to be rude. i wonder why xrtw helped you anyway

this is why i hate helping noobs
