### ISSUE TITLE
Hi renzu !! I very like your script but I have some error with that !!

### ISSUE THREAD

**Issue by tronghiep199x** [renzuzu/renzu_garage#56]
I take out car from the garage !! And that car not hidden in garage when I taked it !!
So well !! I can take out that car unlimit in garage !! Can you fix it??

![Screenshot (63)](https://user-images.githubusercontent.com/86585715/127527705-b137af44-fd03-4a5c-85ec-3e192e021a9b.png)
![Screenshot (64)](https://user-images.githubusercontent.com/86585715/127527714-ad9342a2-6234-469f-bb03-65d8e2ae91f7.png)

**Comment by renzuzu** [comment]
Can you double check if you are updated? Download the main branch

**Comment by tronghiep199x** [comment]
> Can you double check if you are updated? Download the main branch

Yeh !! I had download with last update but it nothing happen !! 
I had setup "esx_realparking", when I parked in "realparking" zone then your garage is not showing that car !! You can check it for that !!

**Comment by tronghiep199x** [comment]
I seen that column in database: "isparked" in "owned_vehicles"
You can check both of that to update you script !! 
I very like your script and thank you so much !!

**Comment by renzuzu** [comment]
this is fixed in latest commits
