### ISSUE TITLE
i found bug if you upgrade or cosme then put to private garage it will not save but if you put it first in public garage it will save 

### ISSUE THREAD

**Issue by bojie12345** [renzuzu/renzu_garage#86]
i found bug if you upgrade or cosme then put to private garage it will not save but if you put it first in public garage it will save

**Comment by renzuzu** [comment]
i will look into this matter , so far i dont experience this, after buying the vehicle, i need proper reporo steps

**Comment by bojie12345** [comment]
ok i will record a video

**Comment by renzuzu** [comment]
i cant reproduce this bug
