### ISSUE TITLE
help

### ISSUE THREAD

**Issue by colector-user** [renzuzu/renzu_garage#88]
https://cdn.discordapp.com/attachments/748504801540571137/880484037725151363/Untitled.png

what this?

**Comment by ryder032** [comment]
hola me encantan y me enamore de los scripts renzu. hoy descargue la ultima actualizacion y me salio este error cuando quise salir del garage... : script:renzu_garage error during NUI callback gotogarage:@renzu_garage/client/cliente.lua : attemp to perform arthmetic on a nil value ( flied 'y')

**Comment by renzuzu** [comment]
@ryder are you updated? sorry for late replying i am creating more scripts atm. soon you will have lscustom made by me.

@colector-user this is what happen if the garage shell has not been deleted
