### ISSUE TITLE
Property Garages

### ISSUE THREAD

**Issue by Dokman** [renzuzu/renzu_garage#94]
it can be possible to make proptery garages like the milton drive apartments? or it's near to impossible?

**Comment by renzuzu** [comment]
what is milton drive apartment?
if you are asking how to trigger the event to show Property garage Here
```
TriggerEvent('renzu_garage:property',"APARTMENT NAME", vector3(-1053.82, -933.09, 3.36))
```
replace the vector3 with the coordinates of door

**Comment by Dokman** [comment]
i mean for example. i have an apartment house, then when i buy  the house it has his garage, how i can show the garage of the house?

**Comment by renzuzu** [comment]
hello i already give you the event.

do you want the garage to be available only after purchase?
it will be complex to sync it to housing script, but its possible.

let me know the details and usecases so i can update it

**Comment by Dokman** [comment]
oh yes that i was meaning using the properties to establish the garages but i was thinking it too and it's very complex, it can be a way checking the properties that you have bought but... it's still difficult...

**Comment by renzuzu** [comment]
Even if we make a new function for that purpose.
You will still need to edit your housing script.

The best way to do this is edit your housing script

Example. The menu of owner from door.

And insert a new menu for opening a garage by using the event for the property above.

The default from garage config

The property ia enable for all doors in coordinates

You can disable it. And manually trigger it from door menu of housing
