### ISSUE TITLE
Private Garage enter position?

### ISSUE THREAD

**Issue by Dokman** [renzuzu/renzu_garage#96]
In owned garages they have a buycoord but to enter is the same, i think the best way to achieve a good result is to have a enter_garage_coord but how it can be done? in the thread to open the garage the only way is the buy coords how i can check if they are bought?

**Comment by renzuzu** [comment]
what your goal?
check if garage is owned?
the private garage is for sale for all even if its already bought by other players.

there is a handler for Checking if you already bought the garage or not.

or do you mean you want a different coords for buycoords and enter garage coord?

it can be done but im not sure if all will be happy for that

**Comment by Dokman** [comment]
i mean for example i have 2 garages. Then the buycoord is the "{marker}" to enter into the garage. but i think it can be changed into another "{marker}" for example in the "Business Office" there have to be like 2 garages one in the bottom part and another into the top part. So one enters in a way and the other in another way. you know what i mean?
