### ISSUE TITLE
QBCore support

### ISSUE THREAD

**Issue by MazvisS** [renzuzu/renzu_garage#99]
Hi, is there will be a qbcore support?

**Comment by renzuzu** [comment]
it is supported in the past version, but this 1.5 version its not supported anymore.

as the garage is still continue to grow every feature adds.
its hard to maintain two framework in every update.

maybe in future. when i feel there is not much to add and fix anymore

**Comment by Mazvis1** [comment]
Okay, thank you

**Comment by Phantomawe** [comment]
Has this been updated for work with the most recent now as I am getting issues with QBCore where it won't let me load the vehicles and it seems to be multiple mods... [https://i.imgur.com/UeRMBx6.png](url)
